In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import sqlite3

In [4]:
conn = sqlite3.connect('database.sqlite')
cur = conn.cursor()

In [3]:
cur.execute("""SELECT *
               FROM Matches
               ;""").fetchall()

[(1, 'D2', 2009, '2010-04-04', 'Oberhausen', 'Kaiserslautern', 2, 1, 'H'),
 (2, 'D2', 2009, '2009-11-01', 'Munich 1860', 'Kaiserslautern', 0, 1, 'A'),
 (3, 'D2', 2009, '2009-10-04', 'Frankfurt FSV', 'Kaiserslautern', 1, 1, 'D'),
 (4, 'D2', 2009, '2010-02-21', 'Frankfurt FSV', 'Karlsruhe', 2, 1, 'H'),
 (5, 'D2', 2009, '2009-12-06', 'Ahlen', 'Karlsruhe', 1, 3, 'A'),
 (6, 'D2', 2009, '2010-04-03', 'Union Berlin', 'Karlsruhe', 1, 1, 'D'),
 (7, 'D2', 2009, '2009-08-14', 'Paderborn', 'Karlsruhe', 2, 0, 'H'),
 (8, 'D2', 2009, '2010-03-08', 'Bielefeld', 'Karlsruhe', 0, 1, 'A'),
 (9, 'D2', 2009, '2009-09-26', 'Kaiserslautern', 'Karlsruhe', 2, 0, 'H'),
 (10, 'D2', 2009, '2009-11-21', 'Hansa Rostock', 'Karlsruhe', 2, 1, 'H'),
 (11, 'D2', 2009, '2009-12-19', 'Greuther Furth', 'Karlsruhe', 1, 4, 'A'),
 (12, 'D2', 2009, '2010-04-16', 'Koblenz', 'Karlsruhe', 2, 2, 'D'),
 (13, 'D2', 2009, '2010-03-21', 'Oberhausen', 'Karlsruhe', 1, 0, 'H'),
 (14, 'D2', 2009, '2009-09-14', 'Cottbus', 'Karlsruhe', 2, 4, 'A'),
 (15, 'D2', 2009, '2010-05-02', 'Duisburg', 'Karlsruhe', 0, 1, 'A'),
 (16, 'D2', 2009, '2009-10-30', 'Fortuna Dusseldorf', 'Karlsruhe', 1, 0, 'H'),
 (17, 'D2', 2009, '2010-01-15', 'Aachen', 'Karlsruhe', 3, 1, 'H'),
 (18, 'D2', 2009, '2009-10-18', 'Augsburg', 'Karlsruhe', 1, 1, 'D'),
 (19, 'D2', 2009, '2010-02-05', 'St Pauli', 'Karlsruhe', 2, 1, 'H'),
 (20, 'D2', 2009, '2009-08-24', 'Munich 1860', 'Karlsruhe', 1, 3, 'A'),
 (21, 'D1', 2009, '2010-02-06', 'Bochum', 'Leverkusen', 1, 1, 'D'),
 (22, 'D1', 2009, '2009-11-22', 'Bayern Munich', 'Leverkusen', 1, 1, 'D'),
 (23, 'D1', 2009, '2010-05-08', "M'gladbach", 'Leverkusen', 1, 1, 'D'),
 (24, 'D1', 2009, '2009-08-08', 'Mainz', 'Leverkusen', 2, 2, 'D'),
 (25, 'D1', 2009, '2009-10-17', 'Hamburg', 'Leverkusen', 0, 0, 'D'),
 (26, 'D1', 2009, '2010-04-17', 'Stuttgart', 'Leverkusen', 2, 1, 'H'),
 (27, 'D1', 2009, '2010-03-20', 'Dortmund', 'Leverkusen', 3, 0, 'H'),
 (28, 'D1', 2009, '2009-10-31', 'Schalke 04', 'Leverkusen', 2, 2, 'D'),
 (29, 'D1', 2009, '2009-08-22', 'Freiburg', 'Leverkusen', 0, 5, 'A'),
 (30, 'D1', 2009, '2010-02-21', 'Werder Bremen', 'Leverkusen', 2, 2, 'D'),
 (31, 'D1', 2009, '2009-12-11', 'Hertha', 'Leverkusen', 2, 2, 'D'),
 (32, 'D1', 2009, '2009-12-05', 'Hannover', 'Leverkusen', 0, 0, 'D'),
 (33, 'D1', 2009, '2010-04-03', 'Ein Frankfurt', 'Leverkusen', 3, 2, 'H'),
 (34, 'D1', 2009, '2009-09-12', 'Wolfsburg', 'Leverkusen', 2, 3, 'A'),
 (35, 'D1', 2009, '2010-01-24', 'Hoffenheim', 'Leverkusen', 0, 3, 'A'),
 (36, 'D1', 2009, '2009-09-26', 'FC Koln', 'Leverkusen', 0, 1, 'A'),
 (37, 'D1', 2009, '2010-03-07', 'Nurnberg', 'Leverkusen', 3, 2, 'H'),
 (38, 'D1', 2009, '2009-11-21', 'Wolfsburg', 'Nurnberg', 2, 3, 'A'),
 (39, 'D1', 2009, '2009-12-05', 'Dortmund', 'Nurnberg', 4, 0, 'H'),
 (40, 'D1', 2009, '2010-04-17', 'Freiburg', 'Nurnberg', 2, 1, 'H'),
 (41, 'D1', 2009, '2010-02-12', "M'gladbach", 'Nurnberg', 2, 1, 'H'),
 (42, 'D1', 2009, '2009-10-03', 'Leverkusen', 'Nurnberg', 4, 0, 'H'),
 (43, 'D1', 2009, '2010-01-17', 'Schalke 04', 'Nurnberg', 1, 0, 'H'),
 (44, 'D1', 2009, '2010-02-27', 'Bochum', 'Nurnberg', 0, 0, 'D'),
 (45, 'D1', 2009, '2010-01-30', 'Hannover', 'Nurnberg', 1, 3, 'A'),
 (46, 'D1', 2009, '2009-08-29', 'Stuttgart', 'Nurnberg', 0, 0, 'D'),
 (47, 'D1', 2009, '2009-11-07', 'Mainz', 'Nurnberg', 1, 0, 'H'),
 (48, 'D1', 2009, '2010-05-01', 'Hamburg', 'Nurnberg', 4, 0, 'H'),
 (49, 'D1', 2009, '2009-09-19', 'Bayern Munich', 'Nurnberg', 2, 1, 'H'),
 (50, 'D1', 2009, '2009-10-24', 'Hoffenheim', 'Nurnberg', 3, 0, 'H'),
 (51, 'D1', 2009, '2009-12-20', 'FC Koln', 'Nurnberg', 3, 0, 'H'),
 (52, 'D1', 2009, '2009-08-15', 'Ein Frankfurt', 'Nurnberg', 1, 1, 'D'),
 (53, 'D1', 2009, '2010-03-27', 'Werder Bremen', 'Nurnberg', 4, 2, 'H'),
 (54, 'D1', 2009, '2010-03-13', 'Hertha', 'Nurnberg', 1, 2, 'A'),
 (55, 'D1', 2009, '2009-09-13', 'FC Koln', 'Schalke 04', 1, 2, 'A'),
 (56, 'D1', 2009, '2009-11-28', "M'gladbach", 'Schalke 04', 1, 0, 'H'),
 (57, 'D1', 2009, '2009-11-07', 'Bayern Munich', 'Schalke 04', 1, 1, 'D'),
 (58, 'D1', 2009, '2010-02-06', 'Freiburg', 'Schalke 04', 0, 0, 'D'),
 (59, 'D1', 2009, '2009-08-08', 'Nurnberg', 'Schalke 04', 1, 2, 'A'),
 (60, 'D1', 2009, '2010-04-24', 'Hertha', 'Schalke 04', 0, 1, 'A'),
 (61, 'D1', 2009, '2009-12-12', 'Werder Bremen', 'Schalke 04', 0, 2, 'A'),
 (62, 'D1', 2009, '2010-05-08', 'Mainz', 'Schalke 04', 0, 0, 'D'),
 (63, 'D1', 2009, '2009-10-17', 'Stuttgart', 'Schalke 04', 1, 2, 'A'),
 (64, 'D1', 2009, '2010-03-21', 'Hamburg', 'Schalke 04', 2, 2, 'D'),
 (65, 'D1', 2009, '2010-01-23', 'Bochum', 'Schalke 04', 2, 2, 'D'),
 (66, 'D1', 2009, '2010-03-06', 'Ein Frankfurt', 'Schalke 04', 1, 4, 'A'),
 (67, 'D1', 2009, '2009-09-26', 'Dortmund', 'Schalke 04', 0, 1, 'A'),
 (68, 'D1', 2009, '2010-02-21', 'Wolfsburg', 'Schalke 04', 2, 1, 'H'),
 (69, 'D1', 2009, '2010-03-27', 'Leverkusen', 'Schalke 04', 0, 2, 'A'),
 (70, 'D1', 2009, '2009-08-21', 'Hoffenheim', 'Schalke 04', 0, 0, 'D'),
 (71, 'D1', 2009, '2010-04-10', 'Hannover', 'Schalke 04', 4, 2, 'H'),
 (72, 'D1', 2009, '2009-10-24', 'Hannover', 'Stuttgart', 1, 0, 'H'),
 (73, 'D1', 2009, '2010-04-10', 'Hertha', 'Stuttgart', 0, 1, 'A'),
 (74, 'D1', 2009, '2010-05-08', 'Hoffenheim', 'Stuttgart', 1, 1, 'D'),
 (75, 'D1', 2009, '2009-09-12', 'Hamburg', 'Stuttgart', 3, 1, 'H'),
 (76, 'D1', 2009, '2009-08-22', 'Dortmund', 'Stuttgart', 1, 1, 'D'),
 (77, 'D1', 2009, '2010-03-06', 'Werder Bremen', 'Stuttgart', 2, 2, 'D'),
 (78, 'D1', 2009, '2010-03-27', 'Bayern Munich', 'Stuttgart', 1, 2, 'A'),
 (79, 'D1', 2009, '2010-03-12', 'Schalke 04', 'Stuttgart', 2, 1, 'H'),
 (80, 'D1', 2009, '2010-04-23', 'Bochum', 'Stuttgart', 0, 2, 'A'),
 (81, 'D1', 2009, '2009-08-07', 'Wolfsburg', 'Stuttgart', 2, 0, 'H'),
 (82, 'D1', 2009, '2009-09-26', 'Ein Frankfurt', 'Stuttgart', 0, 3, 'A'),
 (83, 'D1', 2009, '2010-02-06', 'Nurnberg', 'Stuttgart', 1, 2, 'A'),
 (84, 'D1', 2009, '2010-02-20', 'FC Koln', 'Stuttgart', 1, 5, 'A'),
 (85, 'D1', 2009, '2009-11-07', "M'gladbach", 'Stuttgart', 0, 0, 'D'),
 (86, 'D1', 2009, '2010-01-22', 'Freiburg', 'Stuttgart', 0, 1, 'A'),
 (87, 'D1', 2009, '2009-11-29', 'Leverkusen', 'Stuttgart', 4, 0, 'H'),
 (88, 'D1', 2009, '2009-12-13', 'Mainz', 'Stuttgart', 1, 1, 'D'),
 (89, 'D1', 2009, '2009-09-20', 'Leverkusen', 'Werder Bremen', 0, 0, 'D'),
 (90, 'D1', 2009, '2009-08-30', 'Hertha', 'Werder Bremen', 2, 3, 'A'),
 (91, 'D1', 2009, '2009-12-06', 'FC Koln', 'Werder Bremen', 0, 0, 'D'),
 (92, 'D1', 2009, '2010-02-27', 'Mainz', 'Werder Bremen', 1, 2, 'A'),
 (93, 'D1', 2009, '2010-02-13', 'Hannover', 'Werder Bremen', 1, 5, 'A'),
 (94, 'D1', 2009, '2010-03-14', 'Hoffenheim', 'Werder Bremen', 0, 1, 'A'),
 (95, 'D1', 2009, '2009-11-21', 'Freiburg', 'Werder Bremen', 0, 6, 'A'),
 (96, 'D1', 2009, '2010-04-03', 'Dortmund', 'Werder Bremen', 2, 1, 'H'),
 (97, 'D1', 2009, '2010-04-17', 'Wolfsburg', 'Werder Bremen', 2, 4, 'A'),
 (98, 'D1', 2009, '2010-05-01', 'Schalke 04', 'Werder Bremen', 0, 2, 'A'),
 (99, 'D1', 2009, '2009-10-04', 'Stuttgart', 'Werder Bremen', 0, 2, 'A'),
 (100, 'D1', 2009, '2009-08-15', 'Bayern Munich', 'Werder Bremen', 1, 1, 'D'),
 (101, 'D1', 2009, '2010-01-30', "M'gladbach", 'Werder Bremen', 4, 3, 'H'),
 (102, 'D1', 2009, '2009-12-20', 'Hamburg', 'Werder Bremen', 2, 1, 'H'),
 (103, 'D1', 2009, '2009-10-31', 'Nurnberg', 'Werder Bremen', 2, 2, 'D'),
 (104, 'D1', 2009, '2009-10-25', 'Bochum', 'Werder Bremen', 1, 4, 'A'),
 (105, 'D1', 2009, '2010-01-16', 'Ein Frankfurt', 'Werder Bremen', 1, 0, 'H'),
 (106, 'D1', 2009, '2009-11-01', 'Ein Frankfurt', 'Bochum', 2, 1, 'H'),
 (107, 'D1', 2009, '2010-04-16', 'FC Koln', 'Bochum', 2, 0, 'H'),
 (108, 'D1', 2009, '2010-03-20', 'Werder Bremen', 'Bochum', 3, 2, 'H'),
 (109, 'D1', 2009, '2009-08-29', 'Leverkusen', 'Bochum', 2, 1, 'H'),
 (110, 'D1', 2009, '2010-01-30', 'Hertha', 'Bochum', 0, 0, 'D'),
 (111, 'D1', 2009, '2009-08-16', 'Schalke 04', 'Bochum', 3, 0, 'H'),
 (112, 'D1', 2009, '2009-12-05', 'Stuttgart', 'Bochum', 1, 1, 'D'),
 (113, 'D1', 2009, '2009-11-22', 'Hamburg', 'Bochum', 0, 1, 'A'),
 (114, 'D1', 2009, '2009-09-25', 'Nurnberg', 'Bochum', 0, 1, 'A'),
 (115, 'D1', 2009, '2009-10-18', 'Dortmund', 'Bochum', 2, 0, 'H'),
 (116, 'D1', 2009, '2010-02-20', 'Mainz', 'Bochum', 0, 0, 'D'),
 (117, 'D1', 2009, '2010-03-06', 'Wolfsburg', 'Bochum', 4, 1, 'H'),
 (118, 'D1', 2009, '2009-09-12', 'Hoffenheim', 'Bochum', 3, 0, 'H'),
 (119, 'D1', 2009, '2009-12-19', 'Hannover', 'Bochum', 2, 3, 'A'),
 (120, 'D1', 2009, '2010-05-01', 'Bayern Munich', 'Bochum', 3, 1, 'H'),
 (121, 'D1', 2009, '2010-04-03', 'Freiburg', 'Bochum', 1, 1, 'D'),
 (122, 'D1', 2009, '2010-01-16', "M'gladbach", 'Bochum', 1, 2, 'A'),
 (123, 'D1', 2009, '2009-11-21', 'Schalke 04', 'Hannover', 2, 0, 'H'),
 (124, 'D1', 2009, '2010-02-20', 'Dortmund', 'Hannover', 4, 1, 'H'),
 (125, 'D1', 2009, '2009-12-12', "M'gladbach", 'Hannover', 5, 3, 'H'),
 (126, 'D1', 2009, '2009-08-22', 'Nurnberg', 'Hannover', 0, 2, 'A'),
 (127, 'D1', 2009, '2010-02-06', 'Hoffenheim', 'Hannover', 2, 1, 'H'),
 (128, 'D1', 2009, '2010-04-17', 'Bayern Munich', 'Hannover', 7, 0, 'H'),
 (129, 'D1', 2009, '2009-10-17', 'Ein Frankfurt', 'Hannover', 2, 1, 'H'),
 (130, 'D1', 2009, '2009-09-13', 'Werder Bremen', 'Hannover', 0, 0, 'D'),
 (131, 'D1', 2009, '2010-05-08', 'Bochum', 'Hannover', 0, 3, 'A'),
 (132, 'D1', 2009, '2010-04-24', 'Leverkusen', 'Hannover', 3, 0, 'H'),
 (133, 'D1', 2009, '2010-03-20', 'Stuttgart', 'Hannover', 2, 0, 'H'),
 (134, 'D1', 2009, '2009-10-31', 'FC Koln', 'Hannover', 0, 1, 'A'),
 (135, 'D1', 2009, '2010-01-23', 'Mainz', 'Hannover', 1, 0, 'H'),
 (136, 'D1', 2009, '2010-04-04', 'Hamburg', 'Hannover', 0, 0, 'D'),
 (137, 'D1', 2009, '2009-09-26', 'Wolfsburg', 'Hannover', 4, 2, 'H'),
 (138, 'D1', 2009, '2009-08-08', 'Hertha', 'Hannover', 1, 0, 'H'),
 (139, 'D1', 2009, '2010-03-06', 'Freiburg', 'Hannover', 1, 2, 'A'),
 (140, 'D2', 2009, '2009-08-21', 'Union Berlin', 'Hansa Rostock', 1, 0, 'H'),
 (141, 'D2', 2009, '2010-02-05', 'Oberhausen', 'Hansa Rostock', 2, 1, 'H'),
 (142, 'D2', 2009, '2010-02-27', 'Greuther Furth', 'Hansa Rostock', 1, 0, 'H'),
 (143, 'D2', 2009, '2009-09-20', 'Augsburg', 'Hansa Rostock', 5, 2, 'H'),
 (144, 'D2', 2009, '2009-11-09', 'Aachen', 'Hansa Rostock', 1, 0, 'H'),
 (145, 'D2', 2009, '2010-04-23', 'Kaiserslautern', 'Hansa Rostock', 0, 1, 'A'),
 (146, 'D2', 2009, '2010-03-14', 'Paderborn', 'Hansa Rostock', 2, 2, 'D'),
 (147, 'D2', 2009, '2010-02-14', 'Koblenz', 'Hansa Rostock', 0, 0, 'D'),
 (148, 'D2', 2009, '2010-03-28', 'St Pauli', 'Hansa Rostock', 2, 0, 'H'),
 (149, 'D2', 2009, '2009-11-27', 'Frankfurt FSV', 'Hansa Rostock', 0, 1, 'A'),
 (150, 'D2', 2009, '2010-04-11', 'Karlsruhe', 'Hansa Rostock', 2, 1, 'H'),
 (151,
  'D2',
  2009,
  '2010-05-09',
  'Fortuna Dusseldorf',
  'Hansa Rostock',
  3,
  1,
  'H'),
 (152, 'D2', 2009, '2009-08-10', 'Bielefeld', 'Hansa Rostock', 3, 1, 'H'),
 (153, 'D2', 2009, '2009-10-24', 'Duisburg', 'Hansa Rostock', 3, 1, 'H'),
 (154, 'D2', 2009, '2009-12-14', 'Cottbus', 'Hansa Rostock', 0, 0, 'D'),
 (155, 'D2', 2009, '2010-01-22', 'Munich 1860', 'Hansa Rostock', 3, 0, 'H'),
 (156, 'D2', 2009, '2009-10-04', 'Ahlen', 'Hansa Rostock', 0, 2, 'A'),
 (157, 'D1', 2009, '2010-05-01', 'Leverkusen', 'Hertha', 1, 1, 'D'),
 (158, 'D1', 2009, '2009-08-23', 'Bochum', 'Hertha', 1, 0, 'H'),
 (159, 'D1', 2009, '2010-03-21', 'Wolfsburg', 'Hertha', 1, 5, 'A'),
 (160, 'D1', 2009, '2010-04-03', 'FC Koln', 'Hertha', 0, 3, 'A'),
 (161, 'D1', 2009, '2009-10-30', 'Dortmund', 'Hertha', 2, 0, 'H'),
 (162, 'D1', 2009, '2009-09-12', 'Mainz', 'Hertha', 2, 1, 'H'),
 (163, 'D1', 2009, '2009-10-17', 'Nurnberg', 'Hertha', 3, 0, 'H'),
 (164, 'D1', 2009, '2010-03-06', 'Hamburg', 'Hertha', 1, 0, 'H'),
 (165, 'D1', 2009, '2010-02-21', 'Freiburg', 'Hertha', 0, 3, 'A'),
 (166, 'D1', 2009, '2010-02-05', 'Werder Bremen', 'Hertha', 2, 1, 'H'),
 (167, 'D1', 2009, '2009-12-19', 'Bayern Munich', 'Hertha', 5, 2, 'H'),
 (168, 'D1', 2009, '2009-12-06', 'Schalke 04', 'Hertha', 2, 0, 'H'),
 (169, 'D1', 2009, '2010-01-16', 'Hannover', 'Hertha', 0, 3, 'A'),
 (170, 'D1', 2009, '2009-09-27', 'Hoffenheim', 'Hertha', 5, 1, 'H'),
 (171, 'D1', 2009, '2009-08-16', "M'gladbach", 'Hertha', 2, 1, 'H'),
 (172, 'D1', 2009, '2010-04-18', 'Ein Frankfurt', 'Hertha', 2, 2, 'D'),
 (173, 'D1', 2009, '2009-11-21', 'Stuttgart', 'Hertha', 1, 1, 'D'),
 (174, 'D1', 2009, '2009-09-26', 'Werder Bremen', 'Mainz', 3, 0, 'H'),
 (175, 'D1', 2009, '2010-03-20', 'Freiburg', 'Mainz', 1, 0, 'H'),
 (176, 'D1', 2009, '2009-08-15', 'Hannover', 'Mainz', 1, 1, 'D'),
 (177, 'D1', 2009, '2010-04-03', 'Nurnberg', 'Mainz', 2, 0, 'H'),
 (178, 'D1', 2009, '2009-08-28', "M'gladbach", 'Mainz', 2, 0, 'H'),
 (179, 'D1', 2009, '2009-12-18', 'Schalke 04', 'Mainz', 1, 0, 'H'),
 (180, 'D1', 2009, '2010-01-16', 'Leverkusen', 'Mainz', 4, 2, 'H'),
 (181, 'D1', 2009, '2010-03-07', 'Hoffenheim', 'Mainz', 0, 1, 'A'),
 (182, 'D1', 2009, '2009-10-17', 'FC Koln', 'Mainz', 1, 0, 'H'),
 (183, 'D1', 2009, '2010-05-01', 'Stuttgart', 'Mainz', 2, 2, 'D'),
 (184, 'D1', 2009, '2010-02-13', 'Hertha', 'Mainz', 1, 1, 'D'),
 (185, 'D1', 2009, '2010-01-30', 'Bayern Munich', 'Mainz', 3, 0, 'H'),
 (186, 'D1', 2009, '2009-10-31', 'Wolfsburg', 'Mainz', 3, 3, 'D'),
 (187, 'D1', 2009, '2009-09-19', 'Bochum', 'Mainz', 2, 3, 'A'),
 (188, 'D1', 2009, '2010-04-17', 'Hamburg', 'Mainz', 0, 1, 'A'),
 (189, 'D1', 2009, '2009-12-05', 'Ein Frankfurt', 'Mainz', 2, 0, 'H'),
 (190, 'D1', 2009, '2009-11-21', 'Dortmund', 'Mainz', 0, 0, 'D'),
 (191, 'D2', 2009, '2010-01-17', 'Koblenz', 'Munich 1860', 2, 2, 'D'),
 (192, 'D2', 2009, '2009-11-20', 'Bielefeld', 'Munich 1860', 0, 1, 'A'),
 (193, 'D2', 2009, '2010-02-14', 'Greuther Furth', 'Munich 1860', 1, 2, 'A'),
 (194, 'D2', 2009, '2010-02-17', 'Karlsruhe', 'Munich 1860', 2, 0, 'H'),
 (195, 'D2', 2009, '2009-11-08', 'Cottbus', 'Munich 1860', 1, 0, 'H'),
 (196, 'D2', 2009, '2009-10-24', 'Frankfurt FSV', 'Munich 1860', 3, 2, 'H'),
 (197, 'D2', 2009, '2009-08-15', 'Hansa Rostock', 'Munich 1860', 2, 1, 'H'),
 (198, 'D2', 2009, '2010-03-29', 'Kaiserslautern', 'Munich 1860', 4, 0, 'H'),
 (199,
  'D2',
  2009,
  '2010-04-18',
  'Fortuna Dusseldorf',
  'Munich 1860',
  2,
  0,
  'H'),
 (200, 'D2', 2009, '2010-05-02', 'Augsburg', 'Munich 1860', 1, 0, 'H'),
 (201, 'D2', 2009, '2010-02-26', 'Paderborn', 'Munich 1860', 3, 1, 'H'),
 (202, 'D2', 2009, '2009-12-06', 'Oberhausen', 'Munich 1860', 0, 1, 'A'),
 (203, 'D2', 2009, '2010-03-15', 'Duisburg', 'Munich 1860', 0, 1, 'A'),
 (204, 'D2', 2009, '2009-08-28', 'Ahlen', 'Munich 1860', 0, 0, 'D'),
 (205, 'D2', 2009, '2009-09-20', 'Aachen', 'Munich 1860', 2, 0, 'H'),
 (206, 'D2', 2009, '2009-10-04', 'St Pauli', 'Munich 1860', 3, 1, 'H'),
 (207, 'D2', 2009, '2009-12-20', 'Union Berlin', 'Munich 1860', 1, 1, 'D'),
 (208, 'D2', 2009, '2009-10-16', 'Oberhausen', 'St Pauli', 1, 3, 'A'),
 (209, 'D2', 2009, '2010-04-17', 'Union Berlin', 'St Pauli', 2, 1, 'H'),
 (210, 'D2', 2009, '2009-11-22', 'Augsburg', 'St Pauli', 3, 2, 'H'),
 (211, 'D2', 2009, '2009-08-17', 'Aachen', 'St Pauli', 0, 5, 'A'),
 (212, 'D2', 2009, '2010-04-05', 'Fortuna Dusseldorf', 'St Pauli', 1, 0, 'H'),
 (213, 'D2', 2009, '2009-09-13', 'Frankfurt FSV', 'St Pauli', 2, 3, 'A'),
 (214, 'D2', 2009, '2010-03-19', 'Cottbus', 'St Pauli', 0, 1, 'A'),
 (215, 'D2', 2009, '2010-01-16', 'Ahlen', 'St Pauli', 0, 2, 'A'),
 (216, 'D2', 2009, '2009-08-28', 'Karlsruhe', 'St Pauli', 0, 4, 'A'),
 (217, 'D2', 2009, '2009-09-26', 'Bielefeld', 'St Pauli', 1, 0, 'H'),
 (218, 'D2', 2009, '2010-05-02', 'Greuther Furth', 'St Pauli', 1, 4, 'A'),
 (219, 'D2', 2009, '2010-01-29', 'Duisburg', 'St Pauli', 0, 2, 'A'),
 (220, 'D2', 2009, '2009-12-05', 'Koblenz', 'St Pauli', 1, 5, 'A'),
 (221, 'D2', 2009, '2010-03-07', 'Munich 1860', 'St Pauli', 2, 1, 'H'),
 (222, 'D2', 2009, '2009-12-20', 'Paderborn', 'St Pauli', 2, 1, 'H'),
 (223, 'D2', 2009, '2010-02-22', 'Kaiserslautern', 'St Pauli', 3, 0, 'H'),
 (224, 'D2', 2009, '2009-11-02', 'Hansa Rostock', 'St Pauli', 0, 2, 'A'),
 (225, 'D1', 2009, '2010-01-29', 'Hamburg', 'Wolfsburg', 1, 1, 'D'),
 (226, 'D1', 2009, '2009-10-03', 'Bochum', 'Wolfsburg', 1, 1, 'D'),
 (227, 'D1', 2009, '2010-05-01', 'Dortmund', 'Wolfsburg', 1, 1, 'D'),
 (228, 'D1', 2009, '2009-09-18', 'Schalke 04', 'Wolfsburg', 1, 2, 'A'),
 (229, 'D1', 2009, '2010-03-27', 'Mainz', 'Wolfsburg', 0, 2, 'A'),
 (230, 'D1', 2009, '2010-02-13', 'Leverkusen', 'Wolfsburg', 2, 1, 'H'),
 (231, 'D1', 2009, '2009-11-07', 'Hoffenheim', 'Wolfsburg', 1, 2, 'A'),
 (232, 'D1', 2009, '2010-01-16', 'Stuttgart', 'Wolfsburg', 3, 1, 'H'),
 (233, 'D1', 2009, '2009-10-25', 'Hertha', 'Wolfsburg', 0, 0, 'D'),
 (234, 'D1', 2009, '2010-03-13', "M'gladbach", 'Wolfsburg', 0, 4, 'A'),
 (235, 'D1', 2009, '2009-08-15', 'FC Koln', 'Wolfsburg', 1, 3, 'A'),
 (236, 'D1', 2009, '2009-12-19', 'Ein Frankfurt', 'Wolfsburg', 2, 2, 'D'),
 (237, 'D1', 2009, '2010-04-11', 'Nurnberg', 'Wolfsburg', 0, 2, 'A'),
 (238, 'D1', 2009, '2009-11-28', 'Werder Bremen', 'Wolfsburg', 2, 2, 'D'),
 (239, 'D1', 2009, '2010-04-25', 'Freiburg', 'Wolfsburg', 1, 0, 'H'),
 (240, 'D1', 2009, '2009-08-29', 'Bayern Munich', 'Wolfsburg', 3, 0, 'H'),
 (241, 'D1', 2009, '2010-02-28', 'Hannover', 'Wolfsburg', 0, 1, 'A'),
 (242, 'D1', 2009, '2009-12-04', 'Bayern Munich', "M'gladbach", 2, 1, 'H'),
 (243, 'D1', 2009, '2010-02-19', 'Hoffenheim', "M'gladbach", 2, 2, 'D'),
 (244, 'D1', 2009, '2010-03-06', 'Dortmund', "M'gladbach", 3, 0, 'H'),
 (245, 'D1', 2009, '2009-08-09', 'Bochum', "M'gladbach", 3, 3, 'D'),
 (246, 'D1', 2009, '2009-10-18', 'Wolfsburg', "M'gladbach", 2, 1, 'H'),
 (247, 'D1', 2009, '2010-02-07', 'Mainz', "M'gladbach", 1, 0, 'H'),
 (248, 'D1', 2009, '2010-04-03', 'Stuttgart', "M'gladbach", 2, 1, 'H'),
 (249, 'D1', 2009, '2009-09-12', 'Nurnberg', "M'gladbach", 1, 0, 'H'),
 (250, 'D1', 2009, '2009-10-31', 'Hamburg', "M'gladbach", 2, 3, 'A'),
 (251, 'D1', 2009, '2009-09-27', 'Freiburg', "M'gladbach", 3, 0, 'H'),
 (252, 'D1', 2009, '2010-05-01', 'Hannover', "M'gladbach", 6, 1, 'H'),
 (253, 'D1', 2009, '2010-04-17', 'Schalke 04', "M'gladbach", 3, 1, 'H'),
 (254, 'D1', 2009, '2009-08-23', 'Werder Bremen', "M'gladbach", 3, 0, 'H'),
 (255, 'D1', 2009, '2009-12-19', 'Leverkusen', "M'gladbach", 3, 2, 'H'),
 (256, 'D1', 2009, '2010-01-23', 'Hertha', "M'gladbach", 0, 0, 'D'),
 (257, 'D1', 2009, '2009-11-21', 'Ein Frankfurt', "M'gladbach", 1, 2, 'A'),
 (258, 'D1', 2009, '2010-03-19', 'FC Koln', "M'gladbach", 1, 1, 'D'),
 (259, 'D2', 2009, '2009-11-07', 'Frankfurt FSV', 'Bielefeld', 0, 0, 'D'),
 (260, 'D2', 2009, '2010-01-18', 'Hansa Rostock', 'Bielefeld', 1, 1, 'D'),
 (261, 'D2', 2009, '2009-10-26', 'Paderborn', 'Bielefeld', 0, 2, 'A'),
 (262, 'D2', 2009, '2009-12-04', 'Fortuna Dusseldorf', 'Bielefeld', 3, 2, 'H'),
 (263, 'D2', 2009, '2009-11-30', 'Kaiserslautern', 'Bielefeld', 1, 0, 'H'),
 (264, 'D2', 2009, '2009-12-20', 'Oberhausen', 'Bielefeld', 0, 0, 'D'),
 (265, 'D2', 2009, '2010-03-12', 'Aachen', 'Bielefeld', 2, 1, 'H'),
 (266, 'D2', 2009, '2009-10-05', 'Karlsruhe', 'Bielefeld', 0, 1, 'A'),
 (267, 'D2', 2009, '2010-04-09', 'Munich 1860', 'Bielefeld', 3, 1, 'H'),
 (268, 'D2', 2009, '2009-09-18', 'Duisburg', 'Bielefeld', 0, 3, 'A'),
 (269, 'D2', 2009, '2010-05-02', 'Union Berlin', 'Bielefeld', 3, 0, 'H'),
 (270, 'D2', 2009, '2010-01-30', 'Augsburg', 'Bielefeld', 3, 1, 'H'),
 (271, 'D2', 2009, '2009-08-29', 'Greuther Furth', 'Bielefeld', 2, 4, 'A'),
 (272, 'D2', 2009, '2010-02-28', 'St Pauli', 'Bielefeld', 0, 1, 'A'),
 (273, 'D2', 2009, '2009-08-16', 'Koblenz', 'Bielefeld', 3, 2, 'H'),
 (274, 'D2', 2009, '2010-03-27', 'Cottbus', 'Bielefeld', 4, 1, 'H'),
 (275, 'D2', 2009, '2010-02-12', 'Ahlen', 'Bielefeld', 0, 1, 'A'),
 (276, 'D2', 2009, '2010-02-26', 'Frankfurt FSV', 'Cottbus', 0, 0, 'D'),
 (277, 'D2', 2009, '2009-10-25', 'St Pauli', 'Cottbus', 1, 1, 'D'),
 (278, 'D2', 2009, '2010-01-29', 'Greuther Furth', 'Cottbus', 1, 0, 'H'),
 (279, 'D2', 2009, '2010-04-04', 'Munich 1860', 'Cottbus', 1, 2, 'A'),
 (280, 'D2', 2009, '2009-09-18', 'Paderborn', 'Cottbus', 5, 1, 'H'),
 (281, 'D2', 2009, '2009-12-04', 'Union Berlin', 'Cottbus', 1, 1, 'D'),

In [5]:
cur.execute("""SELECT *
               FROM Matches
               ;""")
df = pd.DataFrame(cur.fetchall())
df.columns = [x[0] for x in cur.description]
df.head()

,Match_ID,Div,Season,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR
0,1,D2,2009,2010-04-04,Oberhausen,Kaiserslautern,2,1,H
1,2,D2,2009,2009-11-01,Munich 1860,Kaiserslautern,0,1,A
2,3,D2,2009,2009-10-04,Frankfurt FSV,Kaiserslautern,1,1,D
3,4,D2,2009,2010-02-21,Frankfurt FSV,Karlsruhe,2,1,H
4,5,D2,2009,2009-12-06,Ahlen,Karlsruhe,1,3,A

In [6]:
df.tail()

,Match_ID,Div,Season,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR
24620,46770,E0,2016,2017-05-21,Liverpool,Middlesbrough,3,0,H
24621,46771,E0,2016,2017-05-21,Man United,Crystal Palace,2,0,H
24622,46772,E0,2016,2017-05-21,Southampton,Stoke,0,1,A
24623,46773,E0,2016,2017-05-21,Swansea,West Brom,2,1,H
24624,46774,E0,2016,2017-05-21,Watford,Man City,0,5,A

In [7]:
df.columns

Index(['Match_ID', 'Div', 'Season', 'Date', 'HomeTeam', 'AwayTeam', 'FTHG',
       'FTAG', 'FTR'],
      dtype='object')

In [8]:
df

,Match_ID,Div,Season,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR
0,1,D2,2009,2010-04-04,Oberhausen,Kaiserslautern,2,1,H
1,2,D2,2009,2009-11-01,Munich 1860,Kaiserslautern,0,1,A
2,3,D2,2009,2009-10-04,Frankfurt FSV,Kaiserslautern,1,1,D
3,4,D2,2009,2010-02-21,Frankfurt FSV,Karlsruhe,2,1,H
4,5,D2,2009,2009-12-06,Ahlen,Karlsruhe,1,3,A
5,6,D2,2009,2010-04-03,Union Berlin,Karlsruhe,1,1,D
6,7,D2,2009,2009-08-14,Paderborn,Karlsruhe,2,0,H
7,8,D2,2009,2010-03-08,Bielefeld,Karlsruhe,0,1,A
8,9,D2,2009,2009-09-26,Kaiserslautern,Karlsruhe,2,0,H
9,10,D2,2009,2009-11-21,Hansa Rostock,Karlsruhe,2,1,H
10,11,D2,2009,2009-12-19,Greuther Furth,Karlsruhe,1,4,A
11,12,D2,2009,2010-04-16,Koblenz,Karlsruhe,2,2,D
12,13,D2,2009,2010-03-21,Oberhausen,Karlsruhe,1,0,H
13,14,D2,2009,2009-09-14,Cottbus,Karlsruhe,2,4,A
14,15,D2,2009,2010-05-02,Duisburg,Karlsruhe,0,1,A
15,16,D2,2009,2009-10-30,Fortuna Dusseldorf,Karlsruhe,1,0,H
16,17,D2,2009,2010-01-15,Aachen,Karlsruhe,3,1,H
17,18,D2,2009,2009-10-18,Augsburg,Karlsruhe,1,1,D
18,19,D2,2009,2010-02-05,St Pauli,Karlsruhe,2,1,H
19,20,D2,2009,2009-08-24,Munich 1860,Karlsruhe,1,3,A
20,21,D1,2009,2010-02-06,Bochum,Leverkusen,1,1,D
21,22,D1,2009,2009-11-22,Bayern Munich,Leverkusen,1,1,D
22,23,D1,2009,2010-05-08,M'gladbach,Leverkusen,1,1,D
23,24,D1,2009,2009-08-08,Mainz,Leverkusen,2,2,D
24,25,D1,2009,2009-10-17,Hamburg,Leverkusen,0,0,D
25,26,D1,2009,2010-04-17,Stuttgart,Leverkusen,2,1,H
26,27,D1,2009,2010-03-20,Dortmund,Leverkusen,3,0,H
27,28,D1,2009,2009-10-31,Schalke 04,Leverkusen,2,2,D
28,29,D1,2009,2009-08-22,Freiburg,Leverkusen,0,5,A
29,30,D1,2009,2010-02-21,Werder Bremen,Leverkusen,2,2,D
...,...,...,...,...,...,...,...,...,...
24595,46745,E0,2016,2017-05-06,Swansea,Everton,1,0,H
24596,46746,E0,2016,2017-05-07,Arsenal,Man United,2,0,H
24597,46747,E0,2016,2017-05-07,Liverpool,Southampton,0,0,D
24598,46748,E0,2016,2017-05-08,Chelsea,Middlesbrough,3,0,H
24599,46749,E0,2016,2017-05-10,Southampton,Arsenal,0,2,A
24600,46750,E0,2016,2017-05-12,Everton,Watford,1,0,H
24601,46751,E0,2016,2017-05-12,West Brom,Chelsea,0,1,A
24602,46752,E0,2016,2017-05-13,Bournemouth,Burnley,2,1,H
24603,46753,E0,2016,2017-05-13,Man City,Leicester,2,1,H
24604,46754,E0,2016,2017-05-13,Middlesbrough,Southampton,1,2,A
24605,46755,E0,2016,2017-05-13,Stoke,Arsenal,1,4,A
24606,46756,E0,2016,2017-05-13,Sunderland,Swansea,0,2,A
24607,46757,E0,2016,2017-05-14,Crystal Palace,Hull,4,0,H
24608,46758,E0,2016,2017-05-14,Tottenham,Man United,2,1,H
24609,46759,E0,2016,2017-05-14,West Ham,Liverpool,0,4,A
24610,46760,E0,2016,2017-05-15,Chelsea,Watford,4,3,H
24611,46761,E0,2016,2017-05-16,Arsenal,Sunderland,2,0,H
24612,46762,E0,2016,2017-05-16,Man City,West Brom,3,1,H
24613,46763,E0,2016,2017-05-17,Southampton,Man United,0,0,D
24614,46764,E0,2016,2017-05-18,Leicester,Tottenham,1,6,A
24615,46765,E0,2016,2017-05-21,Arsenal,Everton,3,1,H
24616,46766,E0,2016,2017-05-21,Burnley,West Ham,1,2,A
24617,46767,E0,2016,2017-05-21,Chelsea,Sunderland,5,1,H
24618,46768,E0,2016,2017-05-21,Hull,Tottenham,1,7,A
24619,46769,E0,2016,2017-05-21,Leicester,Bournemouth,1,1,D
24620,46770,E0,2016,2017-05-21,Liverpool,Middlesbrough,3,0,H
24621,46771,E0,2016,2017-05-21,Man United,Crystal Palace,2,0,H
24622,46772,E0,2016,2017-05-21,Southampton,Stoke,0,1,A
24623,46773,E0,2016,2017-05-21,Swansea,West Brom,2,1,H
24624,46774,E0,2016,2017-05-21,Watford,Man City,0,5,A

In [9]:
cur.execute("""SELECT name
               FROM sqlite_master
               WHERE type = 'table'
               ORDER BY name
;""").fetchall()

[('Matches',),
 ('Teams',),
 ('Teams_in_Matches',),
 ('Unique_Teams',),
 ('sqlite_sequence',)]

In [10]:
cur.execute("""SELECT *
               FROM teams
;""").fetchall()

[('2017', 'Bayern Munich', '27', '26', '15', '597950000', '22150000', '75000'),
 ('2017', 'Dortmund', '33', '25', '18', '416730000', '12630000', '81359'),
 ('2017', 'Leverkusen', '31', '24', '15', '222600000', '7180000', '30210'),
 ('2017', 'RB Leipzig', '30', '23', '15', '180130000', '6000000', '42959'),
 ('2017', 'Schalke 04', '29', '24', '17', '179550000', '6190000', '62271'),
 ('2017', "M'gladbach", '31', '25', '17', '154400000', '4980000', '54014'),
 ('2017', 'Wolfsburg', '31', '24', '14', '124430000', '4010000', '30000'),
 ('2017', 'FC Koln', '24', '26', '9', '118550000', '4940000', '49968'),
 ('2017', 'Hoffenheim', '31', '24', '14', '107330000', '3460000', '30164'),
 ('2017', 'Hertha', '26', '26', '12', '86800000', '3340000', '74475'),
 ('2017', 'Mainz', '31', '25', '16', '71950000', '2320000', '34000'),
 ('2017', 'Hamburg', '31', '25', '15', '71550000', '2310000', '57376'),
 ('2017', 'Werder Bremen', '32', '26', '19', '69450000', '2170000', '42100'),
 ('2017', 'Ein Frankfurt', '34', '24', '18', '67100000', '1970000', '51500'),
 ('2017', 'Augsburg', '36', '26', '20', '63100000', '1750000', '30660'),
 ('2017', 'Freiburg', '26', '26', '8', '57730000', '2220000', '24000'),
 ('2017', 'Stuttgart', '24', '24', '16', '44750000', '1860000', '60449'),
 ('2017', 'Hannover', '31', '25', '13', '43100000', '1390000', '49200'),
 ('2016', 'Bayern Munich', '33', '25', '18', '595400000', '18040000', '75000'),
 ('2016', 'Dortmund', '32', '24', '17', '321550000', '10050000', '81359'),
 ('2016', 'Leverkusen', '39', '23', '21', '244580000', '6270000', '30210'),
 ('2016', 'Schalke 04', '39', '24', '22', '238750000', '6120000', '62271'),
 ('2016', 'Wolfsburg', '43', '24', '21', '225350000', '5240000', '30000'),
 ('2016', "M'gladbach", '33', '23', '15', '155800000', '4720000', '54014'),
 ('2016', 'Hamburg', '38', '24', '19', '94980000', '2500000', '57376'),
 ('2016', 'Mainz', '39', '23', '22', '85700000', '2200000', '34000'),
 ('2016', 'FC Koln', '30', '24', '13', '77400000', '2580000', '49968'),
 ('2016', 'Hoffenheim', '33', '24', '15', '76550000', '2320000', '30164'),
 ('2016', 'Hertha', '33', '24', '14', '75980000', '2300000', '74475'),
 ('2016', 'Werder Bremen', '41', '25', '19', '75080000', '1830000', '42100'),
 ('2016', 'RB Leipzig', '33', '23', '15', '69180000', '2100000', '42959'),
 ('2016', 'Augsburg', '37', '25', '21', '69000000', '1860000', '30660'),
 ('2016', 'Ein Frankfurt', '35', '23', '21', '66100000', '1890000', '51500'),
 ('2016', 'Freiburg', '36', '24', '13', '40250000', '1120000', '24000'),
 ('2016', 'Ingolstadt', '32', '24', '15', '36680000', '1150000', '15690'),
 ('2016', 'Darmstadt', '39', '26', '17', '32830000', '842000', '17400'),
 ('2015', 'Bayern Munich', '34', '25', '19', '608500000', '17900000', '75000'),
 ('2015', 'Dortmund', '30', '24', '14', '311600000', '10390000', '81359'),
 ('2015', 'Wolfsburg', '35', '25', '19', '265430000', '7580000', '30000'),
 ('2015', 'Schalke 04', '32', '24', '14', '209350000', '6540000', '62271'),
 ('2015', 'Leverkusen', '33', '23', '20', '200750000', '6080000', '30210'),
 ('2015', "M'gladbach", '29', '24', '17', '139550000', '4810000', '54014'),
 ('2015', 'Hoffenheim', '31', '24', '17', '111400000', '3590000', '30164'),
 ('2015', 'Ein Frankfurt', '35', '24', '20', '87500000', '2500000', '51500'),
 ('2015', 'Stuttgart', '34', '24', '17', '82600000', '2430000', '60449'),
 ('2015', 'Hamburg', '35', '25', '17', '74080000', '2120000', '57376'),
 ('2015', 'Hannover', '39', '24', '22', '73580000', '1890000', '49200'),
 ('2015', 'Hertha', '34', '24', '15', '72880000', '2140000', '74475'),
 ('2015', 'Mainz', '39', '24', '22', '67550000', '1730000', '34000'),
 ('2015', 'Augsburg', '39', '25', '20', '62500000', '1600000', '30660'),
 ('2015', 'Werder Bremen', '39', '24', '17', '59500000', '1530000', '42100'),
 ('2015', 'FC Koln', '25', '24', '12', '52050000', '2080000', '49968'),
 ('2015', 'Ingolstadt', '29', '24', '15', '24380000', '841000', '15690'),
 ('2015', 'Darmstadt', '30', '26', '8', '19800000', '660000', '17400'),
 ('2014', 'Bayern Munich', '33', '25', '17', '564180000', '17100000', '75000'),
 ('2014', 'Dortmund', '37', '24', '17', '329800000', '8910000', '81359'),
 ('2014', 'Schalke 04', '36', '23', '15', '213380000', '5930000', '62271'),
 ('2014', 'Wolfsburg', '30', '25', '18', '176130000', '5870000', '30000'),
 ('2014', 'Leverkusen', '26', '24', '14', '166550000', '6410000', '30210'),
 ('2014', 'Hamburg', '38', '24', '21', '114950000', '3030000', '57376'),
 ('2014', "M'gladbach", '27', '25', '14', '107330000', '3980000', '54014'),
 ('2014', 'Hoffenheim', '30', '23', '13', '100030000', '3330000', '30164'),
 ('2014', 'Stuttgart', '30', '24', '14', '97900000', '3260000', '60449'),
 ('2014', 'Hannover', '35', '25', '16', '78050000', '2230000', '49200'),
 ('2014', 'Mainz', '36', '24', '19', '76900000', '2140000', '34000'),
 ('2014', 'Hertha', '30', '25', '16', '76480000', '2550000', '74475'),
 ('2014', 'Ein Frankfurt', '30', '24', '14', '73980000', '2470000', '51500'),
 ('2014', 'Werder Bremen', '36', '23', '16', '58580000', '1630000', '42100'),
 ('2014', 'Freiburg', '30', '24', '13', '56900000', '1900000', '24000'),
 ('2014', 'FC Koln', '27', '24', '14', '43330000', '1600000', '49968'),
 ('2014', 'Augsburg', '35', '25', '17', '42430000', '1210000', '30660'),
 ('2014', 'Paderborn', '28', '25', '8', '22450000', '802000', '15000'),
 ('2013', 'Bayern Munich', '30', '24', '15', '483980000', '16130000', '75000'),
 ('2013', 'Dortmund', '31', '24', '11', '285150000', '9200000', '81359'),
 ('2013', 'Schalke 04', '33', '24', '17', '186950000', '5670000', '62271'),
 ('2013', 'Leverkusen', '33', '24', '14', '141850000', '4300000', '30210'),
 ('2013', 'Wolfsburg', '35', '24', '24', '134730000', '3850000', '30000'),
 ('2013', 'Hamburg', '33', '24', '18', '111700000', '3380000', '57376'),
 ('2013', 'Stuttgart', '32', '24', '16', '100980000', '3160000', '60449'),
 ('2013', "M'gladbach", '28', '24', '14', '94780000', '3380000', '54014'),
 ('2013', 'Ein Frankfurt', '33', '24', '11', '84930000', '2570000', '51500'),
 ('2013', 'Hannover', '35', '24', '20', '83550000', '2390000', '49200'),
 ('2013', 'Hoffenheim', '43', '23', '24', '77080000', '1790000', '30164'),
 ('2013', 'Werder Bremen', '38', '23', '18', '74450000', '1960000', '42100'),
 ('2013', 'Freiburg', '34', '23', '15', '66630000', '1960000', '24000'),
 ('2013', 'Nurnberg', '32', '23', '16', '48880000', '1530000', '50000'),
 ('2013', 'Hertha', '32', '25', '14', '45950000', '1440000', '74475'),
 ('2013', 'Mainz', '31', '26', '16', '45400000', '1460000', '34000'),
 ('2013', 'Augsburg', '34', '24', '16', '43500000', '1280000', '30660'),
 ('2013', 'Braunschweig', '32', '25', '10', '29600000', '925000', '23325'),
 ('2012', 'Bayern Munich', '28', '25', '13', '407300000', '14550000', '75000'),
 ('2012', 'Dortmund', '29', '23', '10', '227680000', '7850000', '81359'),
 ('2012', 'Schalke 04', '28', '24', '17', '171000000', '6110000', '62271'),
 ('2012', 'Wolfsburg', '34', '25', '25', '120330000', '3540000', '30000'),
 ('2012', 'Leverkusen', '32', '23', '11', '115900000', '3620000', '30210'),
 ('2012', 'Hamburg', '28', '24', '17', '110600000', '3950000', '57376'),
 ('2012', 'Stuttgart', '32', '25', '19', '102030000', '3190000', '60449'),
 ('2012', 'Hannover', '32', '25', '18', '88000000', '2750000', '49200'),
 ('2012', 'Hoffenheim', '42', '23', '24', '85030000', '2020000', '30164'),
 ('2012', "M'gladbach", '27', '24', '14', '81000000', '3000000', '54014'),
 ('2012', 'Werder Bremen', '32', '23', '14', '79200000', '2480000', '42100'),
 ('2012', 'Ein Frankfurt', '31', '24', '13', '51200000', '1650000', '51500'),
 ('2012', 'Mainz', '31', '26', '18', '50950000', '1640000', '34000'),
 ('2012', 'Augsburg', '31', '25', '16', '47000000', '1520000', '30660'),
 ('2012', 'Freiburg', '31', '23', '14', '45450000', '1470000', '24000'),
 ('2012', 'Nurnberg', '30', '23', '13', '42650000', '1420000', '50000'),
 ('2012', 'Greuther Furth', '37', '24', '19', '34080000', '921000', '18000'),
 ('2012',
  'Fortuna Dusseldorf',
  '34',
  '25',
  '18',
  '31750000',
  '934000',
  '54600'),
 ('2011', 'Bayern Munich', '24', '25', '11', '335600000', '13980000', '75000'),
 ('2011', 'Dortmund', '28', '24', '12', '158200000', '5650000', '81359'),
 ('2011', 'Leverkusen', '29', '23', '9', '151100000', '5210000', '30210'),
 ('2011', 'Schalke 04', '37', '24', '20', '136730000', '3700000', '62271'),
 ('2011', 'Werder Bremen', '38', '23', '17', '125350000', '3300000', '42100'),
 ('2011', 'Wolfsburg', '44', '25', '28', '122000000', '2770000', '30000'),
 ('2011', 'Hamburg', '36', '23', '23', '103200000', '2870000', '57376'),
 ('2011', 'Stuttgart', '32', '24', '18', '101880000', '3180000', '60449'),
 ('2011', 'Hoffenheim', '34', '23', '20', '93600000', '2750000', '30164'),
 ('2011', 'FC Koln', '31', '24', '17', '69290000', '2240000', '49968'),
 ('2011', 'Hannover', '31', '25', '16', '68850000', '2220000', '49200'),
 ('2011', "M'gladbach", '28', '23', '15', '59080000', '2110000', '54014'),
 ('2011', 'Freiburg', '34', '24', '17', '57400000', '1690000', '24000'),
 ('2011', 'Mainz', '30', '25', '18', '55100000', '1840000', '34000'),
 ('2011', 'Hertha', '30', '24', '16', '50350000', '1680000', '74475'),
 ('2011', 'Kaiserslautern', '36', '23', '20', '50050000', '1390000', '49780'),
 ('2011', 'Nurnberg', '30', '23', '12', '43180000', '1440000', '50000'),
 ('2011', 'Augsburg', '32', '25', '15', '34980000', '1090000', '30660'),
 ('2010', 'Bayern Munich', '31', '25', '17', '284500000', '9180000', '75000'),
 ('2010', 'Wolfsburg', '34', '25', '25', '210730000', '6200000', '30000'),
 ('2010', 'Leverkusen', '30', '24', '12', '146650000', '4890000', '30210'),
 ('2010', 'Werder Bremen', '38', '24', '18', '146550000', '3860000', '42100'),
 ('2010', 'Schalke 04', '36', '24', '23', '139650000', '3880000', '62271'),
 ('2010', 'Hamburg', '30', '25', '20', '132230000', '4410000', '57376'),
 ('2010', 'Dortmund', '31', '24', '16', '114650000', '3700000', '81359'),
 ('2010', 'Stuttgart', '33', '24', '17', '106650000', '3230000', '60449'),
 ('2010', 'Hoffenheim', '34', '23', '19', '98350000', '2890000', '30164'),
 ('2010', "M'gladbach", '34', '25', '19', '69300000', '2040000', '54014'),
 ('2010', 'FC Koln', '38', '24', '19', '62480000', '1640000', '49968'),
 ('2010', 'Ein Frankfurt', '31', '24', '15', '56600000', '1830000', '51500'),
 ('2010', 'Mainz', '28', '26', '15', '45550000', '1630000', '34000'),
 ('2010', 'Hannover', '28', '25', '13', '44630000', '1590000', '49200'),
 ('2010', 'Freiburg', '32', '24', '20', '42800000', '1340000', '24000'),
 ('2010', 'Nurnberg', '32', '24', '14', '38980000', '1220000', '50000'),
 ('2010', 'Kaiserslautern', '30', '24', '18', '37230000', '1240000', '49780'),
 ('2010', 'St Pauli', '30', '26', '3', '29900000', '997000', '29546'),
 ('2009', 'Bayern Munich', '29', '25', '15', '283250000', '9770000', '75000'),
 ('2009', 'Wolfsburg', '31', '25', '19', '155880000', '5030000', '30000'),
 ('2009', 'Hamburg', '35', '24', '19', '145930000', '4170000', '57376'),
 ('2009', 'Werder Bremen', '38', '23', '17', '134000000', '3530000', '42100'),
 ('2009', 'Stuttgart', '34', '24', '14', '125000000', '3680000', '60449'),
 ('2009', 'Schalke 04', '40', '23', '23', '113550000', '2840000', '62271'),
 ('2009', 'Leverkusen', '30', '24', '14', '109050000', '3640000', '30210'),
 ('2009', 'Hoffenheim', '33', '22', '16', '90630000', '2750000', '30164'),
 ('2009', 'Dortmund', '34', '23', '15', '80450000', '2370000', '81359'),
 ('2009', 'Hertha', '33', '24', '22', '76100000', '2310000', '74475'),
 ('2009', 'FC Koln', '33', '24', '18', '72230000', '2190000', '49968'),
 ('2009', 'Hannover', '39', '25', '21', '66880000', '1710000', '49200'),
 ('2009', 'Ein Frankfurt', '36', '25', '19', '62000000', '1720000', '51500'),
 ('2009', "M'gladbach", '30', '25', '15', '45800000', '1530000', '54014'),
 ('2009', 'Bochum', '32', '26', '15', '44550000', '1390000', '29299'),
 ('2009', 'Nurnberg', '32', '24', '15', '42080000', '1310000', '50000'),
 ('2009', 'Mainz', '41', '25', '22', '40450000', '987000', '34000'),
 ('2009', 'Freiburg', '32', '24', '21', '31580000', '987000', '24000'),
 ('2008', 'Bayern Munich', '23', '26', '12', '238900000', '10390000', '75000'),
 ('2008', 'Werder Bremen', '34', '23', '17', '142450000', '4190000', '42100'),
 ('2008', 'Schalke 04', '29', '25', '17', '128000000', '4410000', '62271'),
 ('2008', 'Hamburg', '30', '25', '20', '110300000', '3680000', '57376'),
 ('2008', 'Leverkusen', '26', '25', '13', '97700000', '3760000', '30210'),
 ('2008', 'Dortmund', '35', '24', '23', '94180000', '2690000', '81359'),
 ('2008', 'Stuttgart', '27', '25', '12', '93400000', '3460000', '60449'),
 ('2008', 'Wolfsburg', '31', '24', '20', '84550000', '2730000', '30000'),
 ('2008', 'Hertha', '31', '24', '22', '74800000', '2410000', '74475'),
 ('2008', 'Hannover', '28', '26', '14', '65450000', '2340000', '49200'),
 ('2008', 'Ein Frankfurt', '30', '25', '18', '63050000', '2100000', '51500'),
 ('2008', 'Bochum', '30', '26', '17', '45800000', '1530000', '29299'),
 ('2008', 'Hoffenheim', '32', '23', '15', '44200000', '1380000', '30164'),
 ('2008', "M'gladbach", '29', '25', '16', '40250000', '1390000', '54014'),
 ('2008', 'Karlsruhe', '27', '26', '10', '38850000', '1440000', '29699'),
 ('2008', 'FC Koln', '29', '26', '19', '34150000', '1180000', '49968'),
 ('2008', 'Bielefeld', '27', '26', '11', '30000000', '1110000', '26515'),
 ('2008', 'Cottbus', '34', '26', '21', '29450000', '866000', '22528'),
 ('2007', 'Bayern Munich', '28', '25', '12', '222930000', '7960000', '75000'),
 ('2007', 'Werder Bremen', '29', '24', '14', '129030000', '4450000', '42100'),
 ('2007', 'Stuttgart', '34', '24', '17', '115800000', '3410000', '60449'),
 ('2007', 'Schalke 04', '30', '26', '16', '106900000', '3560000', '62271'),
 ('2007', 'Hamburg', '34', '23', '23', '94750000', '2790000', '57376'),
 ('2007', 'Dortmund', '33', '25', '16', '81350000', '2470000', '81359'),
 ('2007', 'Nurnberg', '31', '25', '19', '70950000', '2290000', '50000'),
 ('2007', 'Leverkusen', '30', '23', '12', '67720000', '2260000', '30210'),
 ('2007', 'Hannover', '28', '27', '13', '61450000', '2190000', '49200'),
 ('2007', 'Wolfsburg', '36', '25', '24', '57450000', '1600000', '30000'),
 ('2007', 'Ein Frankfurt', '33', '24', '16', '54180000', '1640000', '51500'),
 ('2007', 'Hertha', '31', '24', '20', '48700000', '1570000', '74475'),
 ('2007', 'Bochum', '30', '26', '15', '39050000', '1300000', '29299'),
 ('2007', 'Bielefeld', '32', '26', '11', '34050000', '1060000', '26515'),
 ('2007', 'Duisburg', '37', '26', '21', '33630000', '909000', '31514'),
 ('2007', 'Karlsruhe', '27', '25', '9', '27500000', '1020000', '29699'),
 ('2007', 'Hansa Rostock', '28', '25', '12', '23950000', '855000', '29000'),
 ('2007', 'Cottbus', '36', '25', '21', '21250000', '590000', '22528'),
 ('2006', 'Bayern Munich', '29', '26', '15', '166980000', '5760000', '75000'),
 ('2006', 'Werder Bremen', '33', '24', '14', '128680000', '3900000', '42100'),
 ('2006', 'Hamburg', '35', '24', '18', '116430000', '3330000', '57376'),
 ('2006', 'Schalke 04', '29', '24', '14', '87430000', '3010000', '62271'),
 ('2006', 'Dortmund', '31', '23', '14', '79300000', '2560000', '81359'),
 ('2006', 'Stuttgart', '30', '25', '11', '64630000', '2150000', '60449'),
 ('2006', 'Wolfsburg', '30', '26', '21', '64050000', '2140000', '30000'),
 ('2006', 'Leverkusen', '28', '24', '14', '63080000', '2250000', '30210'),
 ('2006', 'Hertha', '30', '24', '17', '57880000', '1930000', '74475'),
 ('2006', 'Ein Frankfurt', '29', '25', '11', '51830000', '1790000', '51500'),
 ('2006', 'Nurnberg', '31', '25', '20', '49150000', '1590000', '50000'),
 ('2006', "M'gladbach", '35', '24', '18', '48350000', '1380000', '54014'),
 ('2006', 'Hannover', '31', '25', '14', '40350000', '1300000', '49200'),
 ('2006', 'Mainz', '33', '25', '16', '35850000', '1090000', '34000'),
 ('2006', 'Bochum', '31', '26', '15', '30850000', '995000', '29299'),
 ('2006', 'Bielefeld', '30', '26', '12', '30550000', '1020000', '26515'),
 ('2006', 'Aachen', '26', '25', '5', '23950000', '921000', '32960'),
 ('2006', 'Cottbus', '30', '25', '17', '17530000', '584000', '22528'),
 ('2005', 'Bayern Munich', '25', '27', '14', '171500000', '6860000', '75000'),
 ('2005', 'Werder Bremen', '28', '24', '13', '93800000', '3350000', '42100'),
 ('2005', 'Schalke 04', '32', '24', '15', '87900000', '2750000', '62271'),
 ('2005', 'Leverkusen', '33', '24', '15', '80630000', '2440000', '30210'),
 ('2005', 'Stuttgart', '30', '26', '13', '79650000', '2660000', '60449'),
 ('2005', 'Hamburg', '32', '24', '17', '73600000', '2300000', '57376'),
 ('2005', 'Hertha', '30', '25', '19', '69650000', '2320000', '74475'),
 ('2005', 'Dortmund', '32', '23', '14', '67700000', '2120000', '81359'),
 ('2005', 'Wolfsburg', '32', '27', '22', '66050000', '2060000', '30000'),
 ('2005', "M'gladbach", '32', '26', '21', '50250000', '1570000', '54014'),
 ('2005', 'FC Koln', '36', '26', '16', '48830000', '1360000', '49968'),
 ('2005', 'Hannover', '29', '25', '12', '44000000', '1520000', '49200'),
 ('2005', 'Nurnberg', '32', '24', '16', '37250000', '1160000', '50000'),
 ('2005', 'Ein Frankfurt', '31', '25', '12', '25600000', '826000', '51500'),
 ('2005', 'Kaiserslautern', '32', '25', '14', '23230000', '726000', '49780'),
 ('2005', 'Duisburg', '31', '27', '10', '22500000', '726000', '31514'),
 ('2005', 'Bielefeld', '31', '26', '15', '21700000', '700000', '26515'),
 ('2005', 'Mainz', '30', '25', '10', '15200000', '507000', '34000'),
 ('2017', 'Union Berlin', '26', '26', '9', '20050000', '771000', '47728'),
 ('2017', 'Braunschweig', '24', '25', '8', '18300000', '763000', '47728'),
 ('2017', 'Nurnberg', '27', '25', '12', '16350000', '606000', '47728'),
 ('2017', 'Kaiserslautern', '33', '23', '13', '16280000', '493000', '47728'),
 ('2017', 'Bochum', '32', '24', '10', '16200000', '506000', '47728'),
 ('2017', 'St Pauli', '28', '26', '9', '16100000', '575000', '47728'),
 ('2017', 'Darmstadt', '26', '25', '10', '15630000', '601000', '47728'),
 ('2017', 'Greuther Furth', '29', '24', '13', '15430000', '532000', '47728'),
 ('2017', 'Bielefeld', '24', '26', '5', '14080000', '586000', '47728'),
 ('2017', 'Heidenheim', '27', '25', '5', '13900000', '515000', '47728'),
 ('2017',
  'Fortuna Dusseldorf',
  '27',
  '25',
  '7',
  '13030000',
  '482000',
  '47728'),
 ('2017', 'Dresden', '24', '25', '3', '12680000', '528000', '47728'),
 ('2017', 'Sandhausen', '28', '26', '8', '11180000', '399000', '47728'),
 ('2017', 'Erzgebirge Aue', '30', '26', '6', '10950000', '365000', '47728'),
 ('2017', 'Duisburg', '30', '26', '12', '9250000', '308000', '47728'),
 ('2017', 'Kiel', '28', '25', '3', '8300000', '296000', '47728'),
 ('2017', 'Regensburg', '24', '25', '5', '6250000', '260000', '47728'),
 ('2017', 'Ingolstadt', '26', '25', '11', '26230000', '1010000', '47728'),
 ('2016', 'Stuttgart', '32', '24', '20', '52380000', '1640000', '47728'),
 ('2016', 'Hannover', '33', '23', '15', '40600000', '1230000', '47728'),
 ('2016', 'Munich 1860', '39', '24', '21', '25350000', '650000', '47728'),
 ('2016', 'Nurnberg', '36', '24', '16', '22100000', '614000', '47728'),
 ('2016', 'St Pauli', '35', '24', '11', '21830000', '642000', '47728'),
 ('2016', 'Union Berlin', '33', '25', '12', '20630000', '625000', '47728'),
 ('2016', 'Kaiserslautern', '35', '23', '14', '20400000', '583000', '47728'),
 ('2016', 'Karlsruhe', '40', '23', '15', '18800000', '470000', '47728'),
 ('2016',
  'Fortuna Dusseldorf',
  '32',
  '24',
  '10',
  '18700000',
  '584000',
  '47728'),
 ('2016', 'Braunschweig', '27', '25', '13', '18650000', '691000', '47728'),
 ('2016', 'Greuther Furth', '38', '24', '17', '17300000', '455000', '47728'),
 ('2016', 'Bochum', '35', '22', '10', '15180000', '434000', '47728'),
 ('2016', 'Bielefeld', '32', '25', '6', '14050000', '439000', '47728'),
 ('2016', 'Heidenheim', '28', '23', '7', '13050000', '466000', '47728'),
 ('2016', 'Sandhausen', '29', '25', '8', '12350000', '426000', '47728'),
 ('2016', 'Dresden', '30', '24', '5', '9650000', '322000', '47728'),
 ('2016',

In [170]:
cur.execute("""SELECT *
               FROM teams
               ;""")
df = pd.DataFrame(cur.fetchall())
df.columns = [x[0] for x in cur.description]
print(len(df))
df.head()

468

,Season,TeamName,KaderHome,AvgAgeHome,ForeignPlayersHome,OverallMarketValueHome,AvgMarketValueHome,StadiumCapacity
0,2017,Bayern Munich,27,26,15,597950000,22150000,75000
1,2017,Dortmund,33,25,18,416730000,12630000,81359
2,2017,Leverkusen,31,24,15,222600000,7180000,30210
3,2017,RB Leipzig,30,23,15,180130000,6000000,42959
4,2017,Schalke 04,29,24,17,179550000,6190000,62271

In [87]:
cur.execute("""SELECT Teamname
               FROM teams
               ;""")
df = pd.DataFrame(cur.fetchall())
df.columns = [x[0] for x in cur.description]
print(len(df))
df.head()

468

        TeamName
0  Bayern Munich
1       Dortmund
2     Leverkusen
3     RB Leipzig
4     Schalke 04

In [13]:
df.columns

Index(['TeamName'], dtype='object')

In [14]:
cur.execute("""SELECT Match_ID, Season, SUM(FTHG and FTAG) AS total_goals
               FROM matches
               WHERE Season = '2011'
               
               ;""")
df = pd.DataFrame(cur.fetchall())
df.columns = [x[0] for x in cur.description]
print(len(df))
df

1

   Match_ID  Season  total_goals
0     44874    2011          533

In [171]:
cur.execute("""SELECT *
               FROM matches
               WHERE Season = '2011'
               
               ;""")
df = pd.DataFrame(cur.fetchall())
df.columns = [x[0] for x in cur.description]
print(len(df))
df.head()

992

   Match_ID Div  Season        Date   HomeTeam       AwayTeam  FTHG  FTAG FTR
0      1092  D1    2011  2012-03-31   Nurnberg  Bayern Munich     0     1   A
1      1093  D1    2011  2011-12-11  Stuttgart  Bayern Munich     1     2   A
2      1094  D1    2011  2011-08-13  Wolfsburg  Bayern Munich     0     1   A
3      1095  D1    2011  2011-11-27      Mainz  Bayern Munich     3     2   H
4      1096  D1    2011  2012-02-18   Freiburg  Bayern Munich     0     0   D

In [204]:
cur.execute("""SELECT Hometeam AS Team, sum(FTHG) AS Home_goals,Season , Div
               FROM matches
               WHERE Season = '2011'
               GROUP BY 1
                       
;""")
dfhome= pd.DataFrame(cur.fetchall())
dfhome.columns = [x[0] for x in cur.description]
dfhome.head()

            Team  Home_goals  Season Div
0         Aachen          15    2011  D2
1        Arsenal          39    2011  E0
2    Aston Villa          20    2011  E0
3       Augsburg          20    2011  D1
4  Bayern Munich          49    2011  D1

In [206]:
cur.execute("""SELECT AwayTeam AS Team, sum(FTAG) AS Away_goals,Season, Div
               FROM matches
               WHERE Season = '2011'
               GROUP BY 1
               ;""")
dfAway = pd.DataFrame(cur.fetchall())
dfAway.columns = [x[0] for x in cur.description]
dfAway.head()

            Team  Away_goals  Season Div
0         Aachen          15    2011  D2
1        Arsenal          35    2011  E0
2    Aston Villa          17    2011  E0
3       Augsburg          16    2011  D1
4  Bayern Munich          28    2011  D1

In [207]:
new_df1 = pd.merge(dfhome,dfAway, how='inner', on=['Team'])
new_df1.head()

            Team  Home_goals  Season_x Div_x  Away_goals  Season_y Div_y
0         Aachen          15      2011    D2          15      2011    D2
1        Arsenal          39      2011    E0          35      2011    E0
2    Aston Villa          20      2011    E0          17      2011    E0
3       Augsburg          20      2011    D1          16      2011    D1
4  Bayern Munich          49      2011    D1          28      2011    D1

In [208]:
#write a lambda function to create a new table for 
new_df1['Total_goals'] = new_df1.apply(lambda x: x["Home_goals"] + x["Away_goals"], axis=1)
new_df1.head()

,Team,Home_goals,Season_x,Div_x,Away_goals,Season_y,Div_y,Total_goals
0,Aachen,15,2011,D2,15,2011,D2,30
1,Arsenal,39,2011,E0,35,2011,E0,74
2,Aston Villa,20,2011,E0,17,2011,E0,37
3,Augsburg,20,2011,D1,16,2011,D1,36
4,Bayern Munich,49,2011,D1,28,2011,D1,77

In [209]:
#look here with fresh eyes. you are tired. 3 hrs of sleep.
wins = []
for x in range(0, len(df)):
    if df.FTR[x]== 'H':
       wins.append(df.HomeTeam[x])
    elif df.FTR[x] == 'A':
       wins.append(df.AwayTeam[x])

In [210]:
num_of_wins=[]
for x in new_df1['Team']:
    num_of_wins.append(wins.count(x))

In [211]:
new_df1['num_of_wins'] = num_of_wins
new_df1.head()

,Team,Home_goals,Season_x,Div_x,Away_goals,Season_y,Div_y,Total_goals,num_of_wins
0,Aachen,15,2011,D2,15,2011,D2,30,6
1,Arsenal,39,2011,E0,35,2011,E0,74,21
2,Aston Villa,20,2011,E0,17,2011,E0,37,7
3,Augsburg,20,2011,D1,16,2011,D1,36,8
4,Bayern Munich,49,2011,D1,28,2011,D1,77,23

In [212]:
lost =[]
for x in range(0, len(df)):
    if df.FTR[x]== 'A':
        lost.append(df.HomeTeam[x])
    elif df.FTR[x]=='H':
        lost.append(df.AwayTeam[x])

In [213]:
num_of_lost = []
for x in new_df1['Team']:
    num_of_lost.append(lost.count(x))

In [214]:
new_df1['num_of_lost'] = num_of_lost

In [215]:
new_df1.head()

,Team,Home_goals,Season_x,Div_x,Away_goals,Season_y,Div_y,Total_goals,num_of_wins,num_of_lost
0,Aachen,15,2011,D2,15,2011,D2,30,6,15
1,Arsenal,39,2011,E0,35,2011,E0,74,21,10
2,Aston Villa,20,2011,E0,17,2011,E0,37,7,14
3,Augsburg,20,2011,D1,16,2011,D1,36,8,12
4,Bayern Munich,49,2011,D1,28,2011,D1,77,23,7

In [216]:
# i made a silly mistake here so i had to delete the column i mistakenly duplicated
#del new_df1['num_lost']

new_df1.head()

,Team,Home_goals,Season_x,Div_x,Away_goals,Season_y,Div_y,Total_goals,num_of_wins,num_of_lost
0,Aachen,15,2011,D2,15,2011,D2,30,6,15
1,Arsenal,39,2011,E0,35,2011,E0,74,21,10
2,Aston Villa,20,2011,E0,17,2011,E0,37,7,14
3,Augsburg,20,2011,D1,16,2011,D1,36,8,12
4,Bayern Munich,49,2011,D1,28,2011,D1,77,23,7

In [ ]:
# do histogram here

In [18]:
#2nd get dates and use darksky to check whether it rained on that day or not
Date = list(df.Date.unique())
Date

['2012-03-31',
 '2011-12-11',
 '2011-08-13',
 '2011-11-27',
 '2012-02-18',
 '2012-01-20',
 '2012-02-04',
 '2012-04-21',
 '2011-09-18',
 '2011-10-23',
 '2011-10-01',
 '2012-03-03',
 '2011-08-27',
 '2012-03-17',
 '2011-11-06',
 '2012-05-05',
 '2012-04-11',
 '2011-12-17',
 '2012-02-03',
 '2011-10-29',
 '2012-01-22',
 '2011-12-03',
 '2012-04-14',
 '2012-03-25',
 '2012-03-10',
 '2012-04-07',
 '2011-11-19',
 '2011-10-14',
 '2011-09-24',
 '2012-04-28',
 '2011-12-18',
 '2012-03-02',
 '2012-03-16',
 '2012-02-17',
 '2011-08-06',
 '2011-11-04',
 '2011-09-16',
 '2011-07-15',
 '2012-05-06',
 '2012-02-11',
 '2011-10-02',
 '2012-03-30',
 '2011-10-22',
 '2011-08-26',
 '2011-08-07',
 '2012-02-24',
 '2011-07-17',
 '2012-02-12',
 '2011-08-22',
 '2011-09-09',
 '2012-04-01',
 '2011-09-25',
 '2012-04-20',
 '2011-11-25',
 '2012-03-09',
 '2011-11-07',
 '2011-09-10',
 '2011-08-21',
 '2011-09-26',
 '2012-03-26',
 '2011-10-30',
 '2012-02-13',
 '2012-02-26',
 '2011-12-19',
 '2012-03-11',
 '2011-11-26',
 '2012-04-23',
 '2011-12-16',
 '2011-11-05',
 '2012-04-10',
 '2012-04-15',
 '2012-02-05',
 '2012-03-04',
 '2011-09-17',
 '2012-01-21',
 '2012-03-18',
 '2012-04-22',
 '2011-08-20',
 '2012-02-10',
 '2012-02-25',
 '2011-12-10',
 '2012-01-29',
 '2011-10-16',
 '2011-08-05',
 '2012-03-23',
 '2011-09-23',
 '2012-01-28',
 '2011-10-15',
 '2012-03-24',
 '2011-11-18',
 '2012-04-29',
 '2011-12-09',
 '2012-04-08',
 '2012-03-12',
 '2011-07-23',
 '2011-10-28',
 '2012-01-27',
 '2011-12-04',
 '2011-09-11',
 '2011-09-30',
 '2012-02-19',
 '2012-04-13',
 '2011-10-21',
 '2011-08-14',
 '2011-09-12',
 '2011-07-18',
 '2011-08-08',
 '2011-07-24',
 '2011-12-13',
 '2011-08-28',
 '2011-08-19',
 '2012-03-14',
 '2011-08-12',
 '2012-03-05',
 '2011-12-02',
 '2011-09-19',
 '2011-07-25',
 '2012-04-02',
 '2012-02-06',
 '2011-11-21',
 '2011-07-22',
 '2011-08-29',
 '2012-04-05',
 '2011-11-28',
 '2011-12-12',
 '2011-11-20',
 '2012-02-27',
 '2011-07-16',
 '2011-10-31',
 '2012-02-20',
 '2011-10-17',
 '2011-12-05',
 '2012-04-16',
 '2011-10-03',
 '2012-03-19',
 '2011-08-15',
 '2011-12-20',
 '2011-12-21',
 '2011-12-22',
 '2011-12-26',
 '2011-12-27',
 '2011-12-30',
 '2011-12-31',
 '2012-01-01',
 '2012-01-02',
 '2012-01-03',
 '2012-01-04',
 '2012-01-11',
 '2012-01-14',
 '2012-01-15',
 '2012-01-16',
 '2012-01-31',
 '2012-02-01',
 '2012-03-13',
 '2012-03-20',
 '2012-03-21',
 '2012-04-06',
 '2012-04-09',
 '2012-04-24',
 '2012-04-30',
 '2012-05-01',
 '2012-05-02',
 '2012-05-07',
 '2012-05-08',
 '2012-05-13']

In [20]:
import requests

In [21]:
# to get the current weather forecast
resp = requests.get("https://api.darksky.net/forecast/45c2523a2abba56c9086bf1bd12e36e1/52.5200,13.4050")
resp.json()

{'latitude': 52.52,
 'longitude': 13.405,
 'timezone': 'Europe/Berlin',
 'currently': {'time': 1572540558,
  'summary': 'Partly Cloudy',
  'icon': 'partly-cloudy-night',
  'precipIntensity': 0,
  'precipProbability': 0,
  'temperature': 38.73,
  'apparentTemperature': 34.99,
  'dewPoint': 30.68,
  'humidity': 0.73,
  'pressure': 1026.1,
  'windSpeed': 4.99,
  'windGust': 7.52,
  'windBearing': 71,
  'cloudCover': 0.34,
  'uvIndex': 0,
  'visibility': 6.161,
  'ozone': 295.3},
 'hourly': {'summary': 'Mostly cloudy throughout the day.',
  'icon': 'rain',
  'data': [{'time': 1572537600,
    'summary': 'Partly Cloudy',
    'icon': 'partly-cloudy-night',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 40.75,
    'apparentTemperature': 37.61,
    'dewPoint': 30.64,
    'humidity': 0.67,
    'pressure': 1025.9,
    'windSpeed': 4.67,
    'windGust': 5.86,
    'windBearing': 71,
    'cloudCover': 0.37,
    'uvIndex': 0,
    'visibility': 6.216,
    'ozone': 293.7},
   {'time': 1572541200,
    'summary': 'Partly Cloudy',
    'icon': 'partly-cloudy-night',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 38.34,
    'apparentTemperature': 34.49,
    'dewPoint': 30.68,
    'humidity': 0.74,
    'pressure': 1026.1,
    'windSpeed': 5.05,
    'windGust': 7.84,
    'windBearing': 72,
    'cloudCover': 0.33,
    'uvIndex': 0,
    'visibility': 6.216,
    'ozone': 295.6},
   {'time': 1572544800,
    'summary': 'Clear',
    'icon': 'clear-night',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 36.42,
    'apparentTemperature': 32.11,
    'dewPoint': 30.7,
    'humidity': 0.8,
    'pressure': 1025.9,
    'windSpeed': 5.2,
    'windGust': 9.16,
    'windBearing': 82,
    'cloudCover': 0.27,
    'uvIndex': 0,
    'visibility': 7.128,
    'ozone': 296.7},
   {'time': 1572548400,
    'summary': 'Clear',
    'icon': 'clear-night',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 35.26,
    'apparentTemperature': 31.51,
    'dewPoint': 30.99,
    'humidity': 0.84,
    'pressure': 1025.8,
    'windSpeed': 4.34,
    'windGust': 9.18,
    'windBearing': 94,
    'cloudCover': 0.19,
    'uvIndex': 0,
    'visibility': 10,
    'ozone': 295.9},
   {'time': 1572552000,
    'summary': 'Clear',
    'icon': 'clear-night',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 34.35,
    'apparentTemperature': 31.23,
    'dewPoint': 30.75,
    'humidity': 0.87,
    'pressure': 1025.6,
    'windSpeed': 3.6,
    'windGust': 8.54,
    'windBearing': 108,
    'cloudCover': 0.11,
    'uvIndex': 0,
    'visibility': 10,
    'ozone': 294.4},
   {'time': 1572555600,
    'summary': 'Clear',
    'icon': 'clear-night',
    'precipIntensity': 0.0002,
    'precipProbability': 0.02,
    'precipType': 'rain',
    'temperature': 33.41,
    'apparentTemperature': 30.18,
    'dewPoint': 29.99,
    'humidity': 0.87,
    'pressure': 1025.4,
    'windSpeed': 3.57,
    'windGust': 8.11,
    'windBearing': 110,
    'cloudCover': 0.05,
    'uvIndex': 0,
    'visibility': 10,
    'ozone': 293},
   {'time': 1572559200,
    'summary': 'Clear',
    'icon': 'clear-night',
    'precipIntensity': 0.0002,
    'precipProbability': 0.02,
    'precipType': 'rain',
    'temperature': 32.6,
    'apparentTemperature': 29.01,
    'dewPoint': 29.14,
    'humidity': 0.87,
    'pressure': 1025.1,
    'windSpeed': 3.79,
    'windGust': 8.11,
    'windBearing': 117,
    'cloudCover': 0.03,
    'uvIndex': 0,
    'visibility': 10,
    'ozone': 291.5},
   {'time': 1572562800,
    'summary': 'Clear',
    'icon': 'clear-night',
    'precipIntensity': 0.0002,
    'precipProbability': 0.01,
    'precipType': 'rain',
    'temperature': 32.1,
    'apparentTemperature': 28.05,
    'dewPoint': 28.25,
    'humidity': 0.86,
    'pressure': 1024.7,
    'windSpeed': 4.13,
    'windGust': 8.33,
    'windBearing': 119,
    'cloudCover': 0.03,
    'uvIndex': 0,
    'visibility': 10,
    'ozone': 290.3},
   {'time': 1572566400,
    'summary': 'Clear',
    'icon': 'clear-night',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 31.75,
    'apparentTemperature': 27.54,
    'dewPoint': 27.44,
    'humidity': 0.84,
    'pressure': 1024.3,
    'windSpeed': 4.23,
    'windGust': 8.92,
    'windBearing': 119,
    'cloudCover': 0.02,
    'uvIndex': 0,
    'visibility': 10,
    'ozone': 290},
   {'time': 1572570000,
    'summary': 'Clear',
    'icon': 'clear-night',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 31.52,
    'apparentTemperature': 26.83,
    'dewPoint': 26.87,
    'humidity': 0.83,
    'pressure': 1023.7,
    'windSpeed': 4.66,
    'windGust': 10.03,
    'windBearing': 117,
    'cloudCover': 0.02,
    'uvIndex': 0,
    'visibility': 10,
    'ozone': 291.7},
   {'time': 1572573600,
    'summary': 'Clear',
    'icon': 'clear-night',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 31.43,
    'apparentTemperature': 26.26,
    'dewPoint': 26.57,
    'humidity': 0.82,
    'pressure': 1022.4,
    'windSpeed': 5.16,
    'windGust': 11.49,
    'windBearing': 118,
    'cloudCover': 0.01,
    'uvIndex': 0,
    'visibility': 10,
    'ozone': 294.5},
   {'time': 1572577200,
    'summary': 'Clear',
    'icon': 'clear-night',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 31.34,
    'apparentTemperature': 25.88,
    'dewPoint': 26.59,
    'humidity': 0.82,
    'pressure': 1021.9,
    'windSpeed': 5.48,
    'windGust': 13,
    'windBearing': 119,
    'cloudCover': 0,
    'uvIndex': 0,
    'visibility': 10,
    'ozone': 296.8},
   {'time': 1572580800,
    'summary': 'Clear',
    'icon': 'clear-night',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 30.88,
    'apparentTemperature': 24.96,
    'dewPoint': 26.63,
    'humidity': 0.84,
    'pressure': 1021.2,
    'windSpeed': 5.92,
    'windGust': 14.33,
    'windBearing': 121,
    'cloudCover': 0.01,
    'uvIndex': 0,
    'visibility': 10,
    'ozone': 298.5},
   {'time': 1572584400,
    'summary': 'Partly Cloudy',
    'icon': 'partly-cloudy-night',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 30.18,
    'apparentTemperature': 23.68,
    'dewPoint': 26.71,
    'humidity': 0.87,
    'pressure': 1020.6,
    'windSpeed': 6.49,
    'windGust': 15.68,
    'windBearing': 123,
    'cloudCover': 0.43,
    'uvIndex': 0,
    'visibility': 10,
    'ozone': 299.6},
   {'time': 1572588000,
    'summary': 'Partly Cloudy',
    'icon': 'partly-cloudy-night',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 30.11,
    'apparentTemperature': 23.47,
    'dewPoint': 26.96,
    'humidity': 0.88,
    'pressure': 1020.2,
    'windSpeed': 6.65,
    'windGust': 17.25,
    'windBearing': 128,
    'cloudCover': 0.39,
    'uvIndex': 0,
    'visibility': 10,
    'ozone': 299.5},
   {'time': 1572591600,
    'summary': 'Partly Cloudy',
    'icon': 'partly-cloudy-day',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 30.46,
    'apparentTemperature': 23.37,
    'dewPoint': 27.48,
    'humidity': 0.89,
    'pressure': 1020,
    'windSpeed': 7.38,
    'windGust': 19.43,
    'windBearing': 130,
    'cloudCover': 0.39,
    'uvIndex': 0,
    'visibility': 10,
    'ozone': 297.1},
   {'time': 1572595200,
    'summary': 'Clear',
    'icon': 'clear-day',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 33.56,
    'apparentTemperature': 26.29,
    'dewPoint': 29.21,
    'humidity': 0.84,
    'pressure': 1019.1,
    'windSpeed': 8.79,
    'windGust': 21.82,
    'windBearing': 135,
    'cloudCover': 0.21,
    'uvIndex': 0,
    'visibility': 10,
    'ozone': 293.5},
   {'time': 1572598800,
    'summary': 'Mostly Cloudy',
    'icon': 'partly-cloudy-day',
    'precipIntensity': 0.0002,
    'precipProbability': 0.02,
    'precipType': 'rain',
    'temperature': 37.16,
    'apparentTemperature': 30.15,
    'dewPoint': 30.97,
    'humidity': 0.78,
    'pressure': 1018,
    'windSpeed': 9.95,
    'windGust': 23.42,
    'windBearing': 140,
    'cloudCover': 0.71,
    'uvIndex': 1,
    'visibility': 10,
    'ozone': 290.5},
   {'time': 1572602400,
    'summary': 'Mostly Cloudy',
    'icon': 'partly-cloudy-day',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 40.59,
    'apparentTemperature': 34.23,
    'dewPoint': 31.68,
    'humidity': 0.7,
    'pressure': 1017.1,
    'windSpeed': 10.33,
    'windGust': 23.5,
    'windBearing': 142,
    'cloudCover': 0.62,
    'uvIndex': 1,
    'visibility': 10,
    'ozone': 289.1},
   {'time': 1572606000,
    'summary': 'Mostly Cloudy',
    'icon': 'partly-cloudy-day',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 44.19,
    'apparentTemperature': 38.47,
    'dewPoint': 31.96,
    'humidity': 0.62,
    'pressure': 1015.7,
    'windSpeed': 10.99,
    'windGust': 22.79,
    'windBearing': 146,
    'cloudCover': 0.85,
    'uvIndex': 1,
    'visibility': 10,
    'ozone': 288.5},
   {'time': 1572609600,
    'summary': 'Overcast',
    'icon': 'cloudy',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 46.86,
    'apparentTemperature': 41.82,
    'dewPoint': 32.35,
    'humidity': 0.57,
    'pressure': 1014.5,
    'windSpeed': 10.93,
    'windGust': 22.37,
    'windBearing': 148,
    'cloudCover': 0.9,
    'uvIndex': 1,
    'visibility': 10,
    'ozone': 288.2},
   {'time': 1572613200,
    'summary': 'Overcast',
    'icon': 'cloudy',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 48.28,
    'apparentTemperature': 43.57,
    'dewPoint': 32.69,
    'humidity': 0.55,
    'pressure': 1013,
    'windSpeed': 11.01,
    'windGust': 22.75,
    'windBearing': 151,
    'cloudCover': 0.94,
    'uvIndex': 1,
    'visibility': 10,
    'ozone': 288.4},
   {'time': 1572616800,
    'summary': 'Overcast',
    'icon': 'cloudy',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 48.18,
    'apparentTemperature': 43.56,
    'dewPoint': 32.94,
    'humidity': 0.55,
    'pressure': 1011.6,
    'windSpeed': 10.63,
    'windGust': 23.43,
    'windBearing': 151,
    'cloudCover': 0.97,
    'uvIndex': 0,
    'visibility': 10,
    'ozone': 288.9},
   {'time': 1572620400,
    'summary': 'Overcast',
    'icon': 'cloudy',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 47.5,
    'apparentTemperature': 42.89,
    'dewPoint': 33.76,
    'humidity': 0.59,
    'pressure': 1010.4,
    'windSpeed': 10.16,
    'windGust': 23.92,
    'windBearing': 151,
    'cloudCover': 1,
    'uvIndex': 0,
    'visibility': 10,
    'ozone': 289.8},
   {'time': 1572624000,
    'summary': 'Overcast',
    'icon': 'cloudy',
    'precipIntensity': 0.0011,
    'precipProbability': 0.04,
    'precipType': 'rain',
    'temperature': 46.1,
    'apparentTemperature': 41.17,
    'dewPoint': 35.01,
    'humidity': 0.65,
    'pressure': 1009.7,
    'windSpeed': 10.1,
    'windGust': 24,
    'windBearing': 152,
    'cloudCover': 1,
    'uvIndex': 0,
    'visibility': 10,
    'ozone': 291},
   {'time': 1572627600,
    'summary': 'Overcast',
    'icon': 'cloudy',
    'precipIntensity': 0.0059,
    'precipProbability': 0.12,
    'precipType': 'rain',
    'temperature': 44.93,
    'apparentTemperature': 39.73,
    'dewPoint': 36.42,
    'humidity': 0.72,
    'pressure': 1009,
    'windSpeed': 10.07,
    'windGust': 23.92,
    'windBearing': 155,
    'cloudCover': 1,
    'uvIndex': 0,
    'visibility': 10,
    'ozone': 292.5},
   {'time': 1572631200,
    'summary': 'Overcast',
    'icon': 'cloudy',
    'precipIntensity': 0.0106,
    'precipProbability': 0.21,
    'precipType': 'rain',
    'temperature': 44.03,
    'apparentTemperature': 38.56,
    'dewPoint': 37.82,
    'humidity': 0.79,
    'pressure': 1008.1,
    'windSpeed': 10.19,
    'windGust': 23.95,
    'windBearing': 159,
    'cloudCover': 1,
    'uvIndex': 0,
    'visibility': 10,
    'ozone': 293.6},
   {'time': 1572634800,
    'summary': 'Overcast',
    'icon': 'cloudy',
    'precipIntensity': 0.0088,
    'precipProbability': 0.27,
    'precipType': 'rain',
    'temperature': 43.87,
    'apparentTemperature': 38.36,
    'dewPoint': 39.18,
    'humidity': 0.83,
    'pressure': 1007.1,
    'windSpeed': 10.19,
    'windGust': 24.26,
    'windBearing': 163,
    'cloudCover': 1,
    'uvIndex': 0,
    'visibility': 10,
    'ozone': 293.7},
   {'time': 1572638400,
    'summary': 'Overcast',
    'icon': 'cloudy',
    'precipIntensity': 0.0059,
    'precipProbability': 0.34,
    'precipType': 'rain',
    'temperature': 44.01,
    'apparentTemperature': 38.58,
    'dewPoint': 40.14,
    'humidity': 0.86,
    'pressure': 1005.8,
    'windSpeed': 10.09,
    'windGust': 24.68,
    'windBearing': 168,
    'cloudCover': 1,
    'uvIndex': 0,
    'visibility': 10,
    'ozone': 293.5},
   {'time': 1572642000,
    'summary': 'Possible Drizzle',
    'icon': 'rain',
    'precipIntensity': 0.0091,
    'precipProbability': 0.46,
    'precipType': 'rain',
    'temperature': 44.07,
    'apparentTemperature': 38.67,
    'dewPoint': 41.06,
    'humidity': 0.89,
    'pressure': 1004.7,
    'windSpeed': 10.07,
    'windGust': 25,
    'windBearing': 169,
    'cloudCover': 1,
    'uvIndex': 0,
    'visibility': 10,
    'ozone': 293.5},
   {'time': 1572645600,
    'summary': 'Possible Drizzle',
    'icon': 'rain',
    'precipIntensity': 0.0126,
    'precipProbability': 0.53,
    'precipType': 'rain',
    'temperature': 44.25,
    'apparentTemperature': 38.87,
    'dewPoint': 41.82,
    'humidity': 0.91,
    'pressure': 1003.6,
    'windSpeed': 10.1,
    'windGust': 25.07,
    'windBearing': 170,
    'cloudCover': 1,
    'uvIndex': 0,
    'visibility': 10,
    'ozone': 294.4},
   {'time': 1572649200,
    'summary': 'Possible Drizzle',
    'icon': 'rain',
    'precipIntensity': 0.0114,
    'precipProbability': 0.49,
    'precipType': 'rain',
    'temperature': 44.46,
    'apparentTemperature': 39.07,
    'dewPoint': 42.56,
    'humidity': 0.93,
    'pressure': 1002.5,
    'windSpeed': 10.27,
    'windGust': 25.02,
    'windBearing': 170,
    'cloudCover': 1,
    'uvIndex': 0,
    'visibility': 10,
    'ozone': 295.5},
   {'time': 1572652800,
    'summary': 'Possible Drizzle',
    'icon': 'rain',
    'precipIntensity': 0.0068,
    'precipProbability': 0.46,
    'precipType': 'rain',
    'temperature': 44.7,
    'apparentTemperature': 39.31,
    'dewPoint': 43.04,
    'humidity': 0.94,
    'pressure': 1001.5,
    'windSpeed': 10.43,
    'windGust': 25.1,
    'windBearing': 170,
    'cloudCover': 1,
    'uvIndex': 0,
    'visibility': 10,
    'ozone': 295.9},
   {'time': 1572656400,
    'summary': 'Possible Drizzle',
    'icon': 'rain',
    'precipIntensity': 0.006,
    'precipProbability': 0.45,
    'precipType': 'rain',
    'temperature': 45.03,
    'apparentTemperature': 39.66,
    'dewPoint': 43.41,
    'humidity': 0.94,
    'pressure': 1000.4,
    'windSpeed': 10.58,
    'windGust': 25.39,
    'windBearing': 170,
    'cloudCover': 1,
    'uvIndex': 0,
    'visibility': 10,
    'ozone': 294.5},
   {'time': 1572660000,
    'summary': 'Possible Drizzle',
    'icon': 'rain',
    'precipIntensity': 0.0092,
    'precipProbability': 0.51,
    'precipType': 'rain',
    'temperature': 45.51,
    'apparentTemperature': 40.25,
    'dewPoint': 43.54,
    'humidity': 0.93,
    'pressure': 999.3,
    'windSpeed': 10.61,
    'windGust': 25.81,
    'windBearing': 170,
    'cloudCover': 1,
    'uvIndex': 0,
    'visibility': 10,
    'ozone': 292.4},
   {'time': 1572663600,
    'summary': 'Possible Drizzle',
    'icon': 'rain',
    'precipIntensity': 0.0126,
    'precipProbability': 0.54,
    'precipType': 'rain',
    'temperature': 45.92,
    'apparentTemperature': 40.75,
    'dewPoint': 43.74,
    'humidity': 0.92,
    'pressure': 998.4,
    'windSpeed': 10.65,
    'windGust': 26.42,
    'windBearing': 170,
    'cloudCover': 1,
    'uvIndex': 0,
    'visibility': 10,
    'ozone': 291.1},
   {'time': 1572667200,
    'summary': 'Possible Drizzle',
    'icon': 'rain',
    'precipIntensity': 0.0157,
    'precipProbability': 0.59,
    'precipType': 'rain',
    'temperature': 46.39,
    'apparentTemperature': 41.32,
    'dewPoint': 44.14,
    'humidity': 0.92,
    'pressure': 997.6,
    'windSpeed': 10.67,
    'windGust': 27.42,
    'windBearing': 172,
    'cloudCover': 1,
    'uvIndex': 0,
    'visibility': 10,
    'ozone': 291.5},
   {'time': 1572670800,
    'summary': 'Possible Light Rain',
    'icon': 'rain',
    'precipIntensity': 0.0223,
    'precipProbability': 0.62,
    'precipType': 'rain',
    'temperature': 46.84,
    'apparentTemperature': 41.85,
    'dewPoint': 44.95,
    'humidity': 0.93,
    'pressure': 997,
    'windSpeed': 10.74,
    'windGust': 28.6,
    'windBearing': 175,
    'cloudCover': 1,
    'uvIndex': 0,
    'visibility': 10,
    'ozone': 292.8},
   {'time': 1572674400,
    'summary': 'Possible Light Rain',
    'icon': 'rain',
    'precipIntensity': 0.0167,
    'precipProbability': 0.59,
    'precipType': 'rain',
    'temperature': 47,
    'apparentTemperature': 42.09,
    'dewPoint': 45.91,
    'humidity': 0.96,
    'pressure': 996.3,
    'windSpeed': 10.64,
    'windGust': 29.33,
    'windBearing': 178,
    'cloudCover': 1,
    'uvIndex': 0,
    'visibility': 10,
    'ozone': 293.8},
   {'time': 1572678000,
    'summary': 'Possible Drizzle',
    'icon': 'rain',
    'precipIntensity': 0.0108,
    'precipProbability': 0.54,
    'precipType': 'rain',
    'temperature': 47.41,
    'apparentTemperature': 42.6,
    'dewPoint': 46.77,
    'humidity': 0.98,
    'pressure': 995.9,
    'windSpeed': 10.62,
    'windGust': 29.25,
    'windBearing': 181,
    'cloudCover': 1,
    'uvIndex': 0,
    'visibility': 10,
    'ozone': 294.1},
   {'time': 1572681600,
    'summary': 'Possible Drizzle',
    'icon': 'rain',
    'precipIntensity': 0.0052,
    'precipProbability': 0.44,
    'precipType': 'rain',
    'temperature': 47.85,
    'apparentTemperature': 43.14,
    'dewPoint': 47.66,
    'humidity': 0.99,
    'pressure': 995.4,
    'windSpeed': 10.66,
    'windGust': 28.74,
    'windBearing': 182,
    'cloudCover': 1,
    'uvIndex': 0,
    'visibility': 10,
    'ozone': 294},
   {'time': 1572685200,
    'summary': 'Possible Light Rain',
    'icon': 'rain',
    'precipIntensity': 0.0208,
    'precipProbability': 0.56,
    'precipType': 'rain',
    'temperature': 48.89,
    'apparentTemperature': 44.51,
    'dewPoint': 48.71,
    'humidity': 0.99,
    'pressure': 995.2,
    'windSpeed': 10.44,
    'windGust': 28.3,
    'windBearing': 184,
    'cloudCover': 1,
    'uvIndex': 1,
    'visibility': 10,
    'ozone': 293.8},
   {'time': 1572688800,
    'summary': 'Possible Drizzle',
    'icon': 'rain',
    'precipIntensity': 0.005,
    'precipProbability': 0.43,
    'precipType': 'rain',
    'temperature': 50.59,
    'apparentTemperature': 50.59,
    'dewPoint': 50.14,
    'humidity': 0.98,
    'pressure': 994.8,
    'windSpeed': 10.32,
    'windGust': 28.24,
    'windBearing': 190,
    'cloudCover': 1,
    'uvIndex': 1,
    'visibility': 10,
    'ozone': 293.3},
   {'time': 1572692400,
    'summary': 'Overcast',
    'icon': 'cloudy',
    'precipIntensity': 0.0029,
    'precipProbability': 0.3,
    'precipType': 'rain',
    'temperature': 52.89,
    'apparentTemperature': 52.89,
    'dewPoint': 51.56,
    'humidity': 0.95,
    'pressure': 994.5,
    'windSpeed': 10.1,
    'windGust': 28.26,
    'windBearing': 198,
    'cloudCover': 0.99,
    'uvIndex': 1,
    'visibility': 10,
    'ozone': 292.7},
   {'time': 1572696000,
    'summary': 'Overcast',
    'icon': 'cloudy',
    'precipIntensity': 0.0025,
    'precipProbability': 0.28,
    'precipType': 'rain',
    'temperature': 54.81,
    'apparentTemperature': 54.81,
    'dewPoint': 52.65,
    'humidity': 0.92,
    'pressure': 994.3,
    'windSpeed': 9.86,
    'windGust': 27.86,
    'windBearing': 206,
    'cloudCover': 0.99,

In [22]:
# to get the weather forecast for that day
resp = requests.get("https://api.darksky.net/forecast/45c2523a2abba56c9086bf1bd12e36e1/52.5200,13.4050,2011-12-11T12:00:00?currently,daily")
resp.json()

{'latitude': 52.52,
 'longitude': 13.405,
 'timezone': 'Europe/Berlin',
 'currently': {'time': 1323601200,
  'summary': 'Mostly Cloudy',
  'icon': 'partly-cloudy-day',
  'precipIntensity': 0,
  'precipProbability': 0,
  'temperature': 38.64,
  'apparentTemperature': 31.81,
  'dewPoint': 30.17,
  'humidity': 0.71,
  'windSpeed': 10.35,
  'windGust': 10.35,
  'windBearing': 237,
  'cloudCover': 0.61,
  'uvIndex': 0,
  'visibility': 6.216},
 'hourly': {'summary': 'Mostly cloudy throughout the day.',
  'icon': 'partly-cloudy-day',
  'data': [{'time': 1323558000,
    'summary': 'Mostly Cloudy',
    'icon': 'partly-cloudy-night',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 37.43,
    'apparentTemperature': 28.54,
    'dewPoint': 30.17,
    'humidity': 0.75,
    'windSpeed': 14.99,
    'windGust': 14.99,
    'windBearing': 259,
    'cloudCover': 0.75,
    'uvIndex': 0,
    'visibility': 6.216},
   {'time': 1323561600,
    'summary': 'Mostly Cloudy',
    'icon': 'partly-cloudy-night',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 37.22,
    'apparentTemperature': 28.67,
    'dewPoint': 30.17,
    'humidity': 0.75,
    'windSpeed': 13.82,
    'windGust': 14.99,
    'windBearing': 251,
    'cloudCover': 0.61,
    'uvIndex': 0,
    'visibility': 6.216},
   {'time': 1323565200,
    'summary': 'Partly Cloudy',
    'icon': 'partly-cloudy-night',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 35.33,
    'apparentTemperature': 27.18,
    'dewPoint': 29.74,
    'humidity': 0.8,
    'windSpeed': 11.51,
    'windGust': 14,
    'windBearing': 241,
    'cloudCover': 0.33,
    'uvIndex': 0,
    'visibility': 6.216},
   {'time': 1323568800,
    'summary': 'Partly Cloudy',
    'icon': 'partly-cloudy-night',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 34.81,
    'apparentTemperature': 26.05,
    'dewPoint': 29.38,
    'humidity': 0.8,
    'windSpeed': 12.67,
    'windGust': 13,
    'windBearing': 252,
    'cloudCover': 0.33,
    'uvIndex': 0,
    'visibility': 6.216},
   {'time': 1323572400,
    'summary': 'Clear',
    'icon': 'clear-night',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 34.81,
    'apparentTemperature': 26.53,
    'dewPoint': 28.94,
    'humidity': 0.79,
    'windSpeed': 11.51,
    'windGust': 11.51,
    'windBearing': 240,
    'cloudCover': 0.19,
    'uvIndex': 0,
    'visibility': 6.216},
   {'time': 1323576000,
    'summary': 'Partly Cloudy',
    'icon': 'partly-cloudy-night',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 35.33,
    'apparentTemperature': 26.71,
    'dewPoint': 29.29,
    'humidity': 0.78,
    'windSpeed': 12.67,
    'windGust': 12.67,
    'windBearing': 239,
    'cloudCover': 0.33,
    'uvIndex': 0,
    'visibility': 6.216},
   {'time': 1323579600,
    'summary': 'Partly Cloudy',
    'icon': 'partly-cloudy-night',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 33.91,
    'apparentTemperature': 25.93,
    'dewPoint': 28.41,
    'humidity': 0.8,
    'windSpeed': 10.35,
    'windGust': 10.99,
    'windBearing': 240,
    'cloudCover': 0.44,
    'uvIndex': 0,
    'visibility': 6.211},
   {'time': 1323583200,
    'summary': 'Mostly Cloudy',
    'icon': 'partly-cloudy-night',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 34.33,
    'apparentTemperature': 27.65,
    'dewPoint': 28.41,
    'humidity': 0.79,
    'windSpeed': 8.05,
    'windGust': 8.05,
    'windBearing': 230,
    'cloudCover': 0.61,
    'uvIndex': 0,
    'visibility': 6.216},
   {'time': 1323586800,
    'summary': 'Mostly Cloudy',
    'icon': 'partly-cloudy-night',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 33.43,
    'apparentTemperature': 25.49,
    'dewPoint': 28.41,
    'humidity': 0.82,
    'windSpeed': 10.01,
    'windGust': 10.01,
    'windBearing': 236,
    'cloudCover': 0.61,
    'uvIndex': 0,
    'visibility': 6.216},
   {'time': 1323590400,
    'summary': 'Partly Cloudy',
    'icon': 'partly-cloudy-day',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 33.43,
    'apparentTemperature': 27.28,
    'dewPoint': 28.41,
    'humidity': 0.82,
    'windSpeed': 6.91,
    'windGust': 6.91,
    'windBearing': 218,
    'cloudCover': 0.5,
    'uvIndex': 0,
    'visibility': 6.216},
   {'time': 1323594000,
    'summary': 'Partly Cloudy',
    'icon': 'partly-cloudy-day',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 35.84,
    'apparentTemperature': 29.49,
    'dewPoint': 29.39,
    'humidity': 0.77,
    'windSpeed': 8.05,
    'windGust': 8.05,
    'windBearing': 220,
    'cloudCover': 0.5,
    'uvIndex': 0,
    'visibility': 6.216},
   {'time': 1323597600,
    'summary': 'Partly Cloudy',
    'icon': 'partly-cloudy-day',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 37.77,
    'apparentTemperature': 31.85,
    'dewPoint': 30.17,
    'humidity': 0.74,
    'windSpeed': 8.05,
    'windGust': 8.05,
    'windBearing': 237,
    'cloudCover': 0.44,
    'uvIndex': 0,
    'visibility': 6.216},
   {'time': 1323601200,
    'summary': 'Mostly Cloudy',
    'icon': 'partly-cloudy-day',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 38.64,
    'apparentTemperature': 31.81,
    'dewPoint': 30.17,
    'humidity': 0.71,
    'windSpeed': 10.35,
    'windGust': 10.35,
    'windBearing': 237,
    'cloudCover': 0.61,
    'uvIndex': 0,
    'visibility': 6.216},
   {'time': 1323604800,
    'summary': 'Mostly Cloudy',
    'icon': 'partly-cloudy-day',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 41.03,
    'apparentTemperature': 34.91,
    'dewPoint': 31.37,
    'humidity': 0.68,
    'windSpeed': 10.01,
    'windGust': 10.01,
    'windBearing': 230,
    'cloudCover': 0.75,
    'uvIndex': 0,
    'visibility': 6.211},
   {'time': 1323608400,
    'summary': 'Mostly Cloudy',
    'icon': 'partly-cloudy-day',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 39.64,
    'apparentTemperature': 33.19,
    'dewPoint': 30.17,
    'humidity': 0.69,
    'windSpeed': 10.01,
    'windGust': 10.01,
    'windBearing': 221,
    'cloudCover': 0.75,
    'uvIndex': 0,
    'visibility': 6.211},
   {'time': 1323612000,
    'summary': 'Mostly Cloudy',
    'icon': 'partly-cloudy-day',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 38.64,
    'apparentTemperature': 32.94,
    'dewPoint': 29.39,
    'humidity': 0.69,
    'windSpeed': 7.99,
    'windGust': 7.99,
    'windBearing': 191,
    'cloudCover': 0.75,
    'uvIndex': 0,
    'visibility': 6.211},
   {'time': 1323615600,
    'summary': 'Clear',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 36.63,
    'apparentTemperature': 31.13,
    'dewPoint': 29.33,
    'humidity': 0.75,
    'windSpeed': 6.91,
    'windGust': 6.91,
    'windBearing': 191,
    'uvIndex': 0,
    'visibility': 6.206},
   {'time': 1323619200,
    'summary': 'Clear',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 35.82,
    'apparentTemperature': 30.16,
    'dewPoint': 29.74,
    'humidity': 0.78,
    'windSpeed': 6.91,
    'windGust': 6.91,
    'windBearing': 191,
    'uvIndex': 0,
    'visibility': 6.206},
   {'time': 1323622800,
    'summary': 'Clear',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 34.82,
    'apparentTemperature': 28.25,
    'dewPoint': 28.86,
    'humidity': 0.79,
    'windSpeed': 8.05,
    'windGust': 8.05,
    'windBearing': 188,
    'uvIndex': 0,
    'visibility': 6.206},
   {'time': 1323626400,
    'summary': 'Clear',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 34.33,
    'apparentTemperature': 27.01,
    'dewPoint': 28.62,
    'humidity': 0.79,
    'windSpeed': 9.21,
    'windGust': 10.01,
    'windBearing': 180,
    'uvIndex': 0,
    'visibility': 6.206},
   {'time': 1323630000,
    'summary': 'Clear',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 34.81,
    'apparentTemperature': 28.28,
    'dewPoint': 28.41,
    'humidity': 0.77,
    'windSpeed': 7.99,
    'windGust': 7.99,
    'windBearing': 171,
    'uvIndex': 0,
    'visibility': 6.206},
   {'time': 1323633600,
    'summary': 'Clear',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 34.81,
    'apparentTemperature': 27.21,
    'dewPoint': 28.41,
    'humidity': 0.77,
    'windSpeed': 10.01,
    'windGust': 10.01,
    'windBearing': 176,
    'uvIndex': 0,
    'visibility': 6.206},
   {'time': 1323637200,
    'summary': 'Clear',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 34.81,
    'apparentTemperature': 27.61,
    'dewPoint': 28.41,
    'humidity': 0.77,
    'windSpeed': 9.21,
    'windGust': 9.21,
    'windBearing': 176,
    'uvIndex': 0,
    'visibility': 6.206},
   {'time': 1323640800,
    'summary': 'Clear',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 33.03,
    'apparentTemperature': 25.41,
    'dewPoint': 28.2,
    'humidity': 0.82,
    'windSpeed': 9.21,
    'windGust': 13,
    'windBearing': 170,
    'uvIndex': 0,
    'visibility': 6.206}]},
 'daily': {'data': [{'time': 1323558000,
    'summary': 'Mostly cloudy throughout the day.',
    'icon': 'partly-cloudy-day',
    'sunriseTime': 1323587280,
    'sunsetTime': 1323615240,
    'moonPhase': 0.54,
    'precipIntensity': 0,
    'precipIntensityMax': 0,
    'precipProbability': 0,
    'temperatureHigh': 41.54,
    'temperatureHighTime': 1323605040,
    'temperatureLow': 30.55,
    'temperatureLowTime': 1323654360,
    'apparentTemperatureHigh': 34.94,
    'apparentTemperatureHighTime': 1323605040,
    'apparentTemperatureLow': 23.2,
    'apparentTemperatureLowTime': 1323658860,
    'dewPoint': 29.25,
    'humidity': 0.77,
    'windSpeed': 9.66,
    'windGust': 15.03,
    'windGustTime': 1323561060,
    'windBearing': 220,
    'cloudCover': 0.52,
    'uvIndex': 0,
    'uvIndexTime': 1323601080,
    'visibility': 6.212,
    'temperatureMin': 32.54,
    'temperatureMinTime': 1323640800,
    'temperatureMax': 41.54,
    'temperatureMaxTime': 1323605040,
    'apparentTemperatureMin': 25.41,
    'apparentTemperatureMinTime': 1323640800,
    'apparentTemperatureMax': 34.94,
    'apparentTemperatureMaxTime': 1323605040}]},
 'flags': {'sources': ['cmc', 'gfs', 'icon', 'isd', 'madis'],
  'nearest-station': 1.219,
  'units': 'us'},
 'offset': 1}

In [23]:
resp = requests.get("https://api.darksky.net/forecast/45c2523a2abba56c9086bf1bd12e36e1/52.5200,13.4050,2011-12-11T12:00:00?currently,daily")
result = resp.json()

In [24]:
resp.json().keys()

dict_keys(['latitude', 'longitude', 'timezone', 'currently', 'hourly', 'daily', 'flags', 'offset'])

In [25]:
resp = requests.get("https://api.darksky.net/forecast/45c2523a2abba56c9086bf1bd12e36e1/52.5200,13.4050,2011-12-11T12:00:00?currently,daily")
result = resp.json()

In [26]:
#result
result.keys()

dict_keys(['latitude', 'longitude', 'timezone', 'currently', 'hourly', 'daily', 'flags', 'offset'])

In [27]:
result['daily']

{'data': [{'time': 1323558000,
   'summary': 'Mostly cloudy throughout the day.',
   'icon': 'partly-cloudy-day',
   'sunriseTime': 1323587280,
   'sunsetTime': 1323615240,
   'moonPhase': 0.54,
   'precipIntensity': 0,
   'precipIntensityMax': 0,
   'precipProbability': 0,
   'temperatureHigh': 41.54,
   'temperatureHighTime': 1323605040,
   'temperatureLow': 30.55,
   'temperatureLowTime': 1323654360,
   'apparentTemperatureHigh': 34.94,
   'apparentTemperatureHighTime': 1323605040,
   'apparentTemperatureLow': 23.2,
   'apparentTemperatureLowTime': 1323658860,
   'dewPoint': 29.25,
   'humidity': 0.77,
   'windSpeed': 9.66,
   'windGust': 15.03,
   'windGustTime': 1323561060,
   'windBearing': 220,
   'cloudCover': 0.52,
   'uvIndex': 0,
   'uvIndexTime': 1323601080,
   'visibility': 6.212,
   'temperatureMin': 32.54,
   'temperatureMinTime': 1323640800,
   'temperatureMax': 41.54,
   'temperatureMaxTime': 1323605040,
   'apparentTemperatureMin': 25.41,
   'apparentTemperatureMinTime': 1323640800,
   'apparentTemperatureMax': 34.94,
   'apparentTemperatureMaxTime': 1323605040}]}

In [28]:
result['daily'].keys()

dict_keys(['data'])

In [29]:
for key in result['daily'].keys():
    print(key, type(result['daily'][key]))

data <class 'list'>

In [30]:
result['daily']['data'][0]['icon']

'partly-cloudy-day'

In [32]:
weather = []
for date in :
    resp = requests.get("https://api.darksky.net/forecast/45c2523a2abba56c9086bf1bd12e36e1/52.5200,13.4050,{}T12:00:00?currently,daily".format(date))
    result = resp.json()
    try:
        weather.append(result['daily']['data'][0]['icon'])
    except:
        weather.append(result['daily']['data'][0]['summary'])
print(weather)

['rain', 'partly-cloudy-day', 'partly-cloudy-day', 'partly-cloudy-day', 'partly-cloudy-day', 'rain', 'partly-cloudy-day', 'partly-cloudy-day', 'rain', 'rain', 'Clear throughout the day.', 'Clear throughout the day.', 'rain', 'Clear throughout the day.', 'rain', 'rain', 'partly-cloudy-day', 'rain', 'partly-cloudy-day', 'Foggy in the morning.', 'rain', 'rain', 'Partly cloudy throughout the day.', 'partly-cloudy-day', 'partly-cloudy-day', 'partly-cloudy-day', 'partly-cloudy-day', 'Partly cloudy throughout the day.', 'Clear throughout the day.', 'Clear throughout the day.', 'rain', 'partly-cloudy-day', 'Clear throughout the day.', 'rain', 'rain', 'Foggy in the morning.', 'partly-cloudy-day', 'partly-cloudy-day', 'rain', 'partly-cloudy-day', 'Clear throughout the day.', 'partly-cloudy-day', 'Clear throughout the day.', 'rain', 'rain', 'rain', 'rain', 'partly-cloudy-day', 'partly-cloudy-day', 'rain', 'partly-cloudy-day', 'Clear throughout the day.', 'Mostly cloudy throughout the day.', 'rain', 'partly-cloudy-day', 'Clear throughout the day.', 'rain', 'Clear throughout the day.', 'Clear throughout the day.', 'Foggy in the morning.', 'rain', 'partly-cloudy-day', 'partly-cloudy-day', 'partly-cloudy-day', 'partly-cloudy-day', 'rain', 'Partly cloudy throughout the day.', 'rain', 'rain', 'partly-cloudy-day', 'partly-cloudy-day', 'partly-cloudy-day', 'Clear throughout the day.', 'partly-cloudy-day', 'partly-cloudy-day', 'partly-cloudy-day', 'partly-cloudy-day', 'Partly cloudy throughout the day.', 'partly-cloudy-day', 'partly-cloudy-day', 'rain', 'Clear throughout the day.', 'rain', 'rain', 'clear-day', 'partly-cloudy-day', 'partly-cloudy-day', 'Clear throughout the day.', 'Clear throughout the day.', 'rain', 'Clear throughout the day.', 'rain', 'Clear throughout the day.', 'rain', 'rain', 'partly-cloudy-day', 'partly-cloudy-day', 'partly-cloudy-day', 'rain', 'Clear throughout the day.', 'rain', 'partly-cloudy-day', 'partly-cloudy-day', 'rain', 'rain', 'rain', 'rain', 'partly-cloudy-day', 'rain', 'partly-cloudy-day', 'rain', 'partly-cloudy-day', 'rain', 'Clear throughout the day.', 'rain', 'rain', 'partly-cloudy-day', 'rain', 'Clear throughout the day.', 'Foggy overnight.', 'rain', 'rain', 'partly-cloudy-day', 'partly-cloudy-day', 'rain', 'Clear throughout the day.', 'rain', 'Clear throughout the day.', 'partly-cloudy-day', 'partly-cloudy-day', 'Clear throughout the day.', 'partly-cloudy-day', 'Clear throughout the day.', 'Clear throughout the day.', 'partly-cloudy-day', 'rain', 'partly-cloudy-day', 'rain', 'partly-cloudy-day', 'rain', 'partly-cloudy-day', 'rain', 'partly-cloudy-day', 'rain', 'rain', 'rain', 'rain', 'partly-cloudy-day', 'partly-cloudy-day', 'partly-cloudy-day', 'snow', 'Clear throughout the day.', 'Clear throughout the day.', 'partly-cloudy-day', 'partly-cloudy-day', 'partly-cloudy-day', 'partly-cloudy-day', 'Clear throughout the day.', 'rain', 'Clear throughout the day.', 'Clear throughout the day.', 'Clear throughout the day.', 'partly-cloudy-day', 'partly-cloudy-day', 'partly-cloudy-day']

In [36]:
weather_report = dict(zip(Date,weather))
weather_report

{'2012-03-31': 'rain',
 '2011-12-11': 'partly-cloudy-day',
 '2011-08-13': 'partly-cloudy-day',
 '2011-11-27': 'partly-cloudy-day',
 '2012-02-18': 'partly-cloudy-day',
 '2012-01-20': 'rain',
 '2012-02-04': 'partly-cloudy-day',
 '2012-04-21': 'partly-cloudy-day',
 '2011-09-18': 'rain',
 '2011-10-23': 'rain',
 '2011-10-01': 'Clear throughout the day.',
 '2012-03-03': 'Clear throughout the day.',
 '2011-08-27': 'rain',
 '2012-03-17': 'Clear throughout the day.',
 '2011-11-06': 'rain',
 '2012-05-05': 'rain',
 '2012-04-11': 'partly-cloudy-day',
 '2011-12-17': 'rain',
 '2012-02-03': 'partly-cloudy-day',
 '2011-10-29': 'Foggy in the morning.',
 '2012-01-22': 'rain',
 '2011-12-03': 'rain',
 '2012-04-14': 'Partly cloudy throughout the day.',
 '2012-03-25': 'partly-cloudy-day',
 '2012-03-10': 'partly-cloudy-day',
 '2012-04-07': 'partly-cloudy-day',
 '2011-11-19': 'partly-cloudy-day',
 '2011-10-14': 'Partly cloudy throughout the day.',
 '2011-09-24': 'Clear throughout the day.',
 '2012-04-28': 'Clear throughout the day.',
 '2011-12-18': 'rain',
 '2012-03-02': 'partly-cloudy-day',
 '2012-03-16': 'Clear throughout the day.',
 '2012-02-17': 'rain',
 '2011-08-06': 'rain',
 '2011-11-04': 'Foggy in the morning.',
 '2011-09-16': 'partly-cloudy-day',
 '2011-07-15': 'partly-cloudy-day',
 '2012-05-06': 'rain',
 '2012-02-11': 'partly-cloudy-day',
 '2011-10-02': 'Clear throughout the day.',
 '2012-03-30': 'partly-cloudy-day',
 '2011-10-22': 'Clear throughout the day.',
 '2011-08-26': 'rain',
 '2011-08-07': 'rain',
 '2012-02-24': 'rain',
 '2011-07-17': 'rain',
 '2012-02-12': 'partly-cloudy-day',
 '2011-08-22': 'partly-cloudy-day',
 '2011-09-09': 'rain',
 '2012-04-01': 'partly-cloudy-day',
 '2011-09-25': 'Clear throughout the day.',
 '2012-04-20': 'Mostly cloudy throughout the day.',
 '2011-11-25': 'rain',
 '2012-03-09': 'partly-cloudy-day',
 '2011-11-07': 'Clear throughout the day.',
 '2011-09-10': 'rain',
 '2011-08-21': 'Clear throughout the day.',
 '2011-09-26': 'Clear throughout the day.',
 '2012-03-26': 'Foggy in the morning.',
 '2011-10-30': 'rain',
 '2012-02-13': 'partly-cloudy-day',
 '2012-02-26': 'partly-cloudy-day',
 '2011-12-19': 'partly-cloudy-day',
 '2012-03-11': 'partly-cloudy-day',
 '2011-11-26': 'rain',
 '2012-04-23': 'Partly cloudy throughout the day.',
 '2011-12-16': 'rain',
 '2011-11-05': 'rain',
 '2012-04-10': 'partly-cloudy-day',
 '2012-04-15': 'partly-cloudy-day',
 '2012-02-05': 'partly-cloudy-day',
 '2012-03-04': 'Clear throughout the day.',
 '2011-09-17': 'partly-cloudy-day',
 '2012-01-21': 'partly-cloudy-day',
 '2012-03-18': 'partly-cloudy-day',
 '2012-04-22': 'partly-cloudy-day',
 '2011-08-20': 'Partly cloudy throughout the day.',
 '2012-02-10': 'partly-cloudy-day',
 '2012-02-25': 'partly-cloudy-day',
 '2011-12-10': 'rain',
 '2012-01-29': 'Clear throughout the day.',
 '2011-10-16': 'rain',
 '2011-08-05': 'rain',
 '2012-03-23': 'clear-day',
 '2011-09-23': 'partly-cloudy-day',
 '2012-01-28': 'partly-cloudy-day',
 '2011-10-15': 'Clear throughout the day.',
 '2012-03-24': 'Clear throughout the day.',
 '2011-11-18': 'rain',
 '2012-04-29': 'Clear throughout the day.',
 '2011-12-09': 'rain',
 '2012-04-08': 'Clear throughout the day.',
 '2012-03-12': 'rain',
 '2011-07-23': 'rain',
 '2011-10-28': 'partly-cloudy-day',
 '2012-01-27': 'partly-cloudy-day',
 '2011-12-04': 'partly-cloudy-day',
 '2011-09-11': 'rain',
 '2011-09-30': 'Clear throughout the day.',
 '2012-02-19': 'rain',
 '2012-04-13': 'partly-cloudy-day',
 '2011-10-21': 'partly-cloudy-day',
 '2011-08-14': 'rain',
 '2011-09-12': 'rain',
 '2011-07-18': 'rain',
 '2011-08-08': 'rain',
 '2011-07-24': 'partly-cloudy-day',
 '2011-12-13': 'rain',
 '2011-08-28': 'partly-cloudy-day',
 '2011-08-19': 'rain',
 '2012-03-14': 'partly-cloudy-day',
 '2011-08-12': 'rain',
 '2012-03-05': 'Clear throughout the day.',
 '2011-12-02': 'rain',
 '2011-09-19': 'rain',
 '2011-07-25': 'partly-cloudy-day',
 '2012-04-02': 'rain',
 '2012-02-06': 'Clear throughout the day.',
 '2011-11-21': 'Foggy overnight.',
 '2011-07-22': 'rain',
 '2011-08-29': 'rain',
 '2012-04-05': 'partly-cloudy-day',
 '2011-11-28': 'partly-cloudy-day',
 '2011-12-12': 'rain',
 '2011-11-20': 'Clear throughout the day.',
 '2012-02-27': 'rain',
 '2011-07-16': 'Clear throughout the day.',
 '2011-10-31': 'partly-cloudy-day',
 '2012-02-20': 'partly-cloudy-day',
 '2011-10-17': 'Clear throughout the day.',
 '2011-12-05': 'partly-cloudy-day',
 '2012-04-16': 'Clear throughout the day.',
 '2011-10-03': 'Clear throughout the day.',
 '2012-03-19': 'partly-cloudy-day',
 '2011-08-15': 'rain',
 '2011-12-20': 'partly-cloudy-day',
 '2011-12-21': 'rain',
 '2011-12-22': 'partly-cloudy-day',
 '2011-12-26': 'rain',
 '2011-12-27': 'partly-cloudy-day',
 '2011-12-30': 'rain',
 '2011-12-31': 'partly-cloudy-day',
 '2012-01-01': 'rain',
 '2012-01-02': 'rain',
 '2012-01-03': 'rain',
 '2012-01-04': 'rain',
 '2012-01-11': 'partly-cloudy-day',
 '2012-01-14': 'partly-cloudy-day',
 '2012-01-15': 'partly-cloudy-day',
 '2012-01-16': 'snow',
 '2012-01-31': 'Clear throughout the day.',
 '2012-02-01': 'Clear throughout the day.',
 '2012-03-13': 'partly-cloudy-day',
 '2012-03-20': 'partly-cloudy-day',
 '2012-03-21': 'partly-cloudy-day',
 '2012-04-06': 'partly-cloudy-day',
 '2012-04-09': 'Clear throughout the day.',
 '2012-04-24': 'rain',
 '2012-04-30': 'Clear throughout the day.',
 '2012-05-01': 'Clear throughout the day.',
 '2012-05-02': 'Clear throughout the day.',
 '2012-05-07': 'partly-cloudy-day',
 '2012-05-08': 'partly-cloudy-day',
 '2012-05-13': 'partly-cloudy-day'}

In [38]:
weather_df = pd.DataFrame.from_dict(weather_report, orient = 'index')
weather_df.columns = ['weather_summary']
weather_df.head()

              weather_summary
2012-03-31               rain
2011-12-11  partly-cloudy-day
2011-08-13  partly-cloudy-day
2011-11-27  partly-cloudy-day
2012-02-18  partly-cloudy-day

In [41]:
weather_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 165 entries, 2012-03-31 to 2012-05-13
Data columns (total 1 columns):
weather_summary    165 non-null object
dtypes: object(1)
memory usage: 2.6+ KB

In [45]:
#join the weather_summary table to the main DataFrame
new = df.join(weather_df, on = 'Date')
new_columns = ['MatchId','Div','Season','Date','Hometeam','FTHG','FTR','WEATHER']
new.head()

,Match_ID,Div,Season,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,weather_summary
0,1092,D1,2011,2012-03-31,Nurnberg,Bayern Munich,0,1,A,rain
1,1093,D1,2011,2011-12-11,Stuttgart,Bayern Munich,1,2,A,partly-cloudy-day
2,1094,D1,2011,2011-08-13,Wolfsburg,Bayern Munich,0,1,A,partly-cloudy-day
3,1095,D1,2011,2011-11-27,Mainz,Bayern Munich,3,2,H,partly-cloudy-day
4,1096,D1,2011,2012-02-18,Freiburg,Bayern Munich,0,0,D,partly-cloudy-day

In [46]:
#checking for the summary stats
new.describe()

           Match_ID  Season        FTHG        FTAG
count    992.000000   992.0  992.000000  992.000000
mean   17979.213710  2011.0    1.612903    1.205645
std    21054.456586     0.0    1.345979    1.202104
min     1092.000000  2011.0    0.000000    0.000000
25%     1339.750000  2011.0    1.000000    0.000000
50%     1587.500000  2011.0    1.000000    1.000000
75%    44626.250000  2011.0    2.000000    2.000000
max    44874.000000  2011.0    8.000000    6.000000

In [50]:
new.groupby('HomeTeam')['FTAG'].sum()

HomeTeam
Aachen                24
Arsenal               17
Aston Villa           25
Augsburg              19
Bayern Munich          6
Blackburn             33
Bochum                23
Bolton                39
Braunschweig          15
Chelsea               24
Cottbus               25
Dortmund              12
Dresden               20
Duisburg              18
Ein Frankfurt         12
Erzgebirge Aue        22
Everton               15
FC Koln               29
Fortuna Dusseldorf    17
Frankfurt FSV         26
Freiburg              20
Fulham                26
Greuther Furth        12
Hamburg               29
Hannover              17
Hansa Rostock         32
Hertha                29
Hoffenheim            17
Ingolstadt            21
Kaiserslautern        28
Karlsruhe             28
Leverkusen            24
Liverpool             16
M'gladbach            10
Mainz                 26
Man City              12
Man United            19
Munich 1860           22
Newcastle             17
Norwich               30
Nurnberg              25
Paderborn             16
QPR                   25
Schalke 04            14
St Pauli              16
Stoke                 20
Stuttgart             17
Sunderland            17
Swansea               18
Tottenham             17
Union Berlin          18
Werder Bremen         23
West Brom             22
Wigan                 27
Wolfsburg             22
Wolves                43
Name: FTAG, dtype: int64

In [53]:
new['Div'].unique()

array(['D1', 'D2', 'E0'], dtype=object)

In [55]:
#simple lazy way to remove E0 which is the premier league
new = new[new.Div!='E0']
new.shape

(612, 10)

In [217]:
new.shape

(612, 11)

In [221]:
new.head()

,Match_ID,Div,Season,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,weather_summary,rainy_day
0,1092,D1,2011,2012-03-31,Nurnberg,Bayern Munich,0,1,A,rain,0
1,1093,D1,2011,2011-12-11,Stuttgart,Bayern Munich,1,2,A,partly-cloudy-day,0
2,1094,D1,2011,2011-08-13,Wolfsburg,Bayern Munich,0,1,A,partly-cloudy-day,0
3,1095,D1,2011,2011-11-27,Mainz,Bayern Munich,3,2,H,partly-cloudy-day,0
4,1096,D1,2011,2012-02-18,Freiburg,Bayern Munich,0,0,D,partly-cloudy-day,0

In [223]:
new[new.weather_summary == 'rain'] = new[new.weather_summary == 'rain'].assign(rainy_day = 1)

In [224]:
new.head()

,Match_ID,Div,Season,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,weather_summary,rainy_day
0,1092,D1,2011,2012-03-31,Nurnberg,Bayern Munich,0,1,A,rain,1
1,1093,D1,2011,2011-12-11,Stuttgart,Bayern Munich,1,2,A,partly-cloudy-day,0
2,1094,D1,2011,2011-08-13,Wolfsburg,Bayern Munich,0,1,A,partly-cloudy-day,0
3,1095,D1,2011,2011-11-27,Mainz,Bayern Munich,3,2,H,partly-cloudy-day,0
4,1096,D1,2011,2012-02-18,Freiburg,Bayern Munich,0,0,D,partly-cloudy-day,0

In [231]:
new.groupby('HomeTeam').sum()

,Match_ID,Season,FTHG,FTAG,rainy_day,game_won,game_loss
HomeTeam,,,,,,,
Aachen,24768,34187,15,24,5,4,7
Augsburg,22397,34187,20,19,7,6,4
Bayern Munich,22898,34187,49,6,4,14,2
Bochum,24898,34187,23,23,5,7,7
Braunschweig,24745,34187,21,15,4,6,3
Cottbus,24780,34187,18,25,5,4,5
Dortmund,22899,34187,44,12,5,14,1
Dresden,25114,34187,30,20,4,8,4
Duisburg,25095,34187,23,18,7,8,7
Ein Frankfurt,25132,34187,38,12,4,11,1
Erzgebirge Aue,24725,34187,19,22,7,5,5
FC Koln,22847,34187,20,29,8,5,8
Fortuna Dusseldorf,24631,34187,35,17,8,11,1
Frankfurt FSV,24592,34187,20,26,8,3,4
Freiburg,22845,34187,24,20,4,6,5
Greuther Furth,24765,34187,46,12,6,14,2
Hamburg,22768,34187,19,29,4,3,7
Hannover,22650,34187,31,17,8,10,0
Hansa Rostock,24888,34187,20,32,8,3,7
Hertha,22644,34187,19,29,7,4,10
Hoffenheim,22362,34187,21,17,5,4,4
Ingolstadt,24661,34187,28,21,7,6,3
Kaiserslautern,22778,34187,12,28,6,2,10
Karlsruhe,25047,34187,23,28,8,8,6
Leverkusen,22743,34187,28,24,8,8,5
M'gladbach,22525,34187,29,10,6,9,1
Mainz,22604,34187,27,26,4,7,7
Munich 1860,24886,34187,35,22,9,10,5
Nurnberg,22710,34187,22,25,6,6,7
Paderborn,24664,34187,28,16,5,9,2
Schalke 04,22695,34187,47,14,3,13,3
St Pauli,24859,34187,36,16,6,12,2
Stuttgart,22703,34187,36,17,4,10,4
Union Berlin,24748,34187,30,18,6,11,4
Werder Bremen,22659,34187,31,23,6,8,5
Wolfsburg,22545,34187,29,22,3,10,5

In [247]:
new['game_won'] = 0
new['game_loss'] = 0
new.head()

,Match_ID,Div,Season,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,weather_summary,rainy_day,game_won,game_loss,rain_win,rain_loss
0,1092,D1,2011,2012-03-31,Nurnberg,Bayern Munich,0,1,A,rain,1,0,0,0,1
1,1093,D1,2011,2011-12-11,Stuttgart,Bayern Munich,1,2,A,partly-cloudy-day,0,0,0,0,1
2,1094,D1,2011,2011-08-13,Wolfsburg,Bayern Munich,0,1,A,partly-cloudy-day,0,0,0,0,1
3,1095,D1,2011,2011-11-27,Mainz,Bayern Munich,3,2,H,partly-cloudy-day,0,0,0,1,0
4,1096,D1,2011,2012-02-18,Freiburg,Bayern Munich,0,0,D,partly-cloudy-day,0,0,0,0,0

In [227]:
new[new.FTR == 'H'] = new[new.FTR == 'H'].assign(game_won = 1)
new[new.FTR == 'A'] = new[new.FTR == 'A'].assign(game_loss = 1)

In [229]:
new.shape

(612, 13)

In [230]:
new.groupby('HomeTeam').sum()

,Match_ID,Season,FTHG,FTAG,rainy_day,game_won,game_loss
HomeTeam,,,,,,,
Aachen,24768,34187,15,24,5,4,7
Augsburg,22397,34187,20,19,7,6,4
Bayern Munich,22898,34187,49,6,4,14,2
Bochum,24898,34187,23,23,5,7,7
Braunschweig,24745,34187,21,15,4,6,3
Cottbus,24780,34187,18,25,5,4,5
Dortmund,22899,34187,44,12,5,14,1
Dresden,25114,34187,30,20,4,8,4
Duisburg,25095,34187,23,18,7,8,7
Ein Frankfurt,25132,34187,38,12,4,11,1
Erzgebirge Aue,24725,34187,19,22,7,5,5
FC Koln,22847,34187,20,29,8,5,8
Fortuna Dusseldorf,24631,34187,35,17,8,11,1
Frankfurt FSV,24592,34187,20,26,8,3,4
Freiburg,22845,34187,24,20,4,6,5
Greuther Furth,24765,34187,46,12,6,14,2
Hamburg,22768,34187,19,29,4,3,7
Hannover,22650,34187,31,17,8,10,0
Hansa Rostock,24888,34187,20,32,8,3,7
Hertha,22644,34187,19,29,7,4,10
Hoffenheim,22362,34187,21,17,5,4,4
Ingolstadt,24661,34187,28,21,7,6,3
Kaiserslautern,22778,34187,12,28,6,2,10
Karlsruhe,25047,34187,23,28,8,8,6
Leverkusen,22743,34187,28,24,8,8,5
M'gladbach,22525,34187,29,10,6,9,1
Mainz,22604,34187,27,26,4,7,7
Munich 1860,24886,34187,35,22,9,10,5
Nurnberg,22710,34187,22,25,6,6,7
Paderborn,24664,34187,28,16,5,9,2
Schalke 04,22695,34187,47,14,3,13,3
St Pauli,24859,34187,36,16,6,12,2
Stuttgart,22703,34187,36,17,4,10,4
Union Berlin,24748,34187,30,18,6,11,4
Werder Bremen,22659,34187,31,23,6,8,5
Wolfsburg,22545,34187,29,22,3,10,5

In [232]:
#creating a new row for the rain day wins and loss
new['rain_win'] = 0
new['rain_loss'] = 0

In [236]:
new.head()

,Match_ID,Div,Season,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,weather_summary,rainy_day,game_won,game_loss,rain_win,rain_loss
0,1092,D1,2011,2012-03-31,Nurnberg,Bayern Munich,0,1,A,rain,1,0,1,0,0
1,1093,D1,2011,2011-12-11,Stuttgart,Bayern Munich,1,2,A,partly-cloudy-day,0,0,1,0,0
2,1094,D1,2011,2011-08-13,Wolfsburg,Bayern Munich,0,1,A,partly-cloudy-day,0,0,1,0,0
3,1095,D1,2011,2011-11-27,Mainz,Bayern Munich,3,2,H,partly-cloudy-day,0,1,0,0,0
4,1096,D1,2011,2012-02-18,Freiburg,Bayern Munich,0,0,D,partly-cloudy-day,0,0,0,0,0

In [242]:
#rainy days wins percentage
new.rain_win.value_counts(normalize=True)

0    1.0
Name: rain_win, dtype: float64

In [244]:
new[new.game_won == 1] = new[new.game_won== 1].assign(rain_win = 1)
new[new.game_loss == 1] = new[new.game_loss == 1].assign(rain_loss = 1)

In [246]:
new.head()

,Match_ID,Div,Season,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,weather_summary,rainy_day,game_won,game_loss,rain_win,rain_loss
0,1092,D1,2011,2012-03-31,Nurnberg,Bayern Munich,0,1,A,rain,1,0,1,0,1
1,1093,D1,2011,2011-12-11,Stuttgart,Bayern Munich,1,2,A,partly-cloudy-day,0,0,1,0,1
2,1094,D1,2011,2011-08-13,Wolfsburg,Bayern Munich,0,1,A,partly-cloudy-day,0,0,1,0,1
3,1095,D1,2011,2011-11-27,Mainz,Bayern Munich,3,2,H,partly-cloudy-day,0,1,0,1,0
4,1096,D1,2011,2012-02-18,Freiburg,Bayern Munich,0,0,D,partly-cloudy-day,0,0,0,0,0

In [ ]:
#class and object

In [251]:
import json

In [250]:
#i put loc=[''] so you can change
loc[0] = first position of the cordinates
loc[1] = second position of the cordinates
class weathergetter(object):
    def _init_(self, loc=['52.520, 13.405']):
        self.lat = loc[0]
        self.long = loc[1]
        self.url = "https://api.darksky.net/forecast/{}}/{},{},{}T12:00:00?currently,daily"

    
    def get_keys(self , path='/Users/flatironschool/.secret/darksky.json' ):
        with open(path) as f:
            keys = json.load.load(f)

In [ ]:
mongodb

In [248]:
import pymongo

In [ ]:
myclient = pymongo.MongoClient("mongodb://127.0.0.1:27017/")
mydb = myclient['example_database']